### PR TITLE
Next SVN commits

### PR DESCRIPTION
**Pull request by Allofich**
https://sourceforge.net/p/dosbox/code-0/4129/ - Partially committed. Other part conflicts.
https://sourceforge.net/p/dosbox/code-0/4130/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4131/ - Skipped. For old 0.74 branch in SVN so irrelevant.
https://sourceforge.net/p/dosbox/code-0/4132/ - Skipped. Conflict
https://sourceforge.net/p/dosbox/code-0/4133/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4134/ - Skipped. Already in DOSBox-X
https://sourceforge.net/p/dosbox/code-0/4135/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4136/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4137/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4138/ - Skipped. Already in DOSBox-X
https://sourceforge.net/p/dosbox/code-0/4139/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4140/ - Skipped. MAME sound
https://sourceforge.net/p/dosbox/code-0/4141/ - Skipped. MAME sound
https://sourceforge.net/p/dosbox/code-0/4142/ - Skipped. MAME sound
https://sourceforge.net/p/dosbox/code-0/4143/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4144/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4145/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4146/ - Skipped. Already in DOSBox-X
https://sourceforge.net/p/dosbox/code-0/4147/ - Skipped. Conflicts
https://sourceforge.net/p/dosbox/code-0/4148/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4149/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4150/ - Compilation fix to 4149, merged in 4149.
https://sourceforge.net/p/dosbox/code-0/4151/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4152/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4153/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4154/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4155/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4156/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4157/ - Skipped. 0.74
https://sourceforge.net/p/dosbox/code-0/4158/ - Skipped. MAME sound
https://sourceforge.net/p/dosbox/code-0/4159/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4160/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4161/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4162/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4163/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4164/ - Relevant part is in this PR.
https://sourceforge.net/p/dosbox/code-0/4165/ - Skipped. Not sure if needed.
https://sourceforge.net/p/dosbox/code-0/4166/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4167/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4168/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4169/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4170/ - Already in DOSBox-X. Just matched comment to SVN.
https://sourceforge.net/p/dosbox/code-0/4171/ - Already in DOSBox-X
https://sourceforge.net/p/dosbox/code-0/4172/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4173/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4174/ - Skipped. Conflicts
https://sourceforge.net/p/dosbox/code-0/4175/ - Skipped. Undone by next committed
https://sourceforge.net/p/dosbox/code-0/4176/ - In this PR

Compiles and runs.

One thing that might need checking, is that in https://sourceforge.net/p/dosbox/code-0/4130/, the `fatDrive` constructor will return early with a failure if `(bytesector != 512)`. Is that limitation OK for PC-98?

### CODE REVIEW

**Comment by Allofich** [comment]
After clicking on "Virtual Memory" in Windows for Workgroups 3.11 in master branch:

krnl386_000

After clicking on it with this PR (fixed by r4168):

krnl386_000

**Comment by joncampbell123** [comment]
What is the change from *5 to *9 exactly in that one commit for Windows 3.11?

**Comment by joncampbell123** [comment]
All is good except that the changes seem to have broken Windows 3.1 and the S3 emulation.

**Comment by Allofich** [comment]
> What is the change from *5 to *9 exactly in that one commit for Windows 3.11?

I don't know, either. The SVN commit message doesn't make it clear.

That's unfortunate that the typecast fixes caused a problem. It would be good (in a way) if the uncover some bug that was hidden by using the wider types, but it may have just been an oversight on my part somewhere. Later, if you haven't figured it out, I'll try and see if I can narrow down the breaking change.

**Comment by joncampbell123** [comment]
@Allofich Looking deeper it seems to be the size of the struct.

The reverted code is preserved in a patch file under REVERTED-EXAMINE-PATCHES.

**Comment by joncampbell123** [comment]
@Allofich I had to revert some drive_fat.cpp changes that DOSBox-X already addressed. Specifically, DOSBox-X's floppy and FAT driver do support nonstandard sector sizes.

It still enforces a standard sector size with INT 13h in IBM PC mode, but in PC-98 mode "non-standard" sector sizes are supported because both floppy and hard disk images can use anything from 128 bytes/sector to 1024 bytes/sector, and some hard disk images use 2048 bytes/sector. The bytes/sector of the FAT filesystem doesn't necessarily match the bytes/sector of the disk image, but is often some power of 2 multiple, so sector conversion is possible.

**Comment by joncampbell123** [comment]
@Allofich Good news. The problem with the memory paging handler problem was that the VGA_MMIO handler (S3 handling) hadn't been updated. The writeX/readX virtual methods hadn't been updated, meaning they had the old function prototype, and therefore did not get called anymore by code using the newer virtual method prototype.

To fix related issues, code has been added to include/paging.h that explicitly makes it a compiler error to try and override the old function prototype.

**Comment by Allofich** [comment]
Great! Thank you for sticking with it and fixing it.

**Pull request merged**
