### PR TITLE
Makefile.am: Don't ignore setcap error with || true

### PR DESCRIPTION
**Pull request by Jookia**
This just changes the output a bit.

Suggested by @rderooy

### CODE REVIEW

**Comment by VVD** [comment]
FreeBSD don't have command `setcap` - why is it mandatory to run it from Makefile?

**Comment by VVD** [comment]
```
# setcap
-bash: setcap: command not found
# uname -srm
FreeBSD 13.2-RELEASE-p8 amd64
```

**Comment by rderooy** [comment]
Your point being?

I suspect there may be slightly more Linux users than *bsd users

As such, either fix the makefile in such a way that it does not remove the setcap for Linux systems, or don't use `make install`.

**Comment by VVD** [comment]
Run it on Linux only. Isn't it obvious?

**Comment by Jookia** [comment]
It's not mandatory. This PR checks if it exists. Are you having build errors or is this nitpicking?

**Comment by VVD** [comment]
This PR remove ` || true`.

During build I get error:
```
command -v setcap >/dev/null && setcap cap_net_raw=ep /wrkdirs/usr/ports/emulators/dosbox-x/work/stage/usr/local/bin/dosbox-x
*** Error code 127 (ignored)
```
But look like "build farm" can ignore this error.

P.S. I'm a FreeBSD ports maintainer and working on update port emulators/dosbox-x.

**Comment by Jookia** [comment]
Do you not have the command 'command'?

**Comment by VVD** [comment]
Thanks for explanation.
Never used command `command`.
And sorry for noise.

**Pull request closed without merging**
