### PR TITLE
Updated keyboard, codepages and regional settings

### PR DESCRIPTION
**Pull request by rderooy**
Update README.md to reflect recent changes to the code.

This would ideally be applied when a new release is made, to reflect the release version.

### CODE REVIEW

**Comment by Wengier** [comment]
@rderooy I appreciate the updates, but I think the section ("International keyboard layouts and codepages") should probably be moved to the Wiki instead, which is the actual DOSBox-X user guide.

**Comment by rderooy** [comment]
@Wengier I had thought of that. It was simply because README.md already had a section on keyboards that I kept it.

I was actually thinking on a "Input" page on the wiki, handling keyboards, mice and joysticks. But that will not be done in the next few days, so I would suggest to add this commit for now, and then for the next round, when that page will hopefully exist, it can be removed from README.md.

**Comment by Wengier** [comment]
@rderooy I think you can mention the country auto-detection with “country=0” too, although it only works on Windows, and I don’t know if the detection is 100% reliable.

**Comment by Wengier** [comment]
@rderooy I have already created a DOSBox-X regional settings page in the DOSBox-X Wiki:

https://github.com/Wengier/dosbox-x-wiki/wiki/Guide:Regional-settings-in-DOSBox%E2%80%90X

**Pull request merged**
