### PR TITLE
Add CP 850/858 for host to guest code page mapping

### PR DESCRIPTION
**Pull request by Wengier**
As mentioned in Issue #1762, DOSBox-X currently only supports  code page 437, 866 and 932, but not 850 or 858, which are very common for users. So I added support for these code pages to DOSBox-X.

Also allowed to change the "usecodepages" and "startwait" config options via the config -set command.

Tested to ensure the code works.

### CODE REVIEW

**Comment by Wengier** [comment]
I have added code page 852 (Latin II) and 855 (Cyrillic) too, which are useful for Central and Eastern European users.

**Comment by rderooy** [comment]
I tested the PR locally on Linux with both SDL1 and SDL2 binaries. It worked great. I can now list files with a Ó in the filename when using an appropriate codepage, and can type the character when using an appropriate international keyboard layout.

Hoping this PR still makes it for the next release version.

**Comment by joncampbell123** [comment]
@Wengier Speaking of release, this month's release is going to be a little late due to how busy I've been with work the past few weeks. Expect a release of perhaps August 2nd or 3rd.

**Comment by Wengier** [comment]
@joncampbell123 I see. I think I can understand it because I have to make time to do work myself too.

**Pull request merged**
