### PR TITLE
Small fixes and enhancements in VHD code

### PR DESCRIPTION
**Pull request by maxpat78**
- ConvertFixed in bios_vhd.cpp can now do better partition detection
- enforced checks in VHDMAKE -convert
- cosmetic changes in VHDInfo struct
- updated help strings (VHDMAKE)

### CODE REVIEW

**Comment by maron2000** [comment]
Great work!

BTW, I see the warning below, but I think contributors should make the code compatible with c++11.
You can find such comment in configure.ac, and maybe somewhere else as well.
@joncampbell123 do you have any further comments?

```
dos_programs.cpp:7806:19: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    char* sizes = "BKMGT";
                  ^
```

**Comment by joncampbell123** [comment]
> Great work!
> 
> BTW, I see the warning below, but I think contributors should make the code compatible with c++11. You can find such comment in configure.ac, and maybe somewhere else as well. @joncampbell123 do you have any further comments?
> 
> ```
> dos_programs.cpp:7806:19: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
>     char* sizes = "BKMGT";
>                   ^
> ```

It might be possible to silence that warning by changing it to:

    const char* sizes = "BKMGT";

**Comment by maron2000** [comment]
Just tried on MinGW build but seems good.

Current code
before

After changing to `const char* sizes = "BKMGT";`, no warning regarding line 7806
after

**Comment by maxpat78** [comment]
@maron2000 @joncampbell123 I've noticed the "Not everyone wants to put underscores" patch... I suppose it originated from my access/_access and strdup/_strdup change in code to satisfy VC++? What is the more C++-in-DOSBox-X conformant way to write that?

**Comment by maron2000** [comment]
@maxpat78  The fix by @joncampbell123 was required to build successfully on Linux and mac, while your original code failed.
https://github.com/joncampbell123/dosbox-x/actions/runs/6301953916

**Pull request merged**
