### PR TITLE
Improved mapper GUI

### PR DESCRIPTION
**Pull request by aybe**
This is a revamp of the mapper... basically, 

- try create a real keyboard layout
- adjust the general layout, add margins
- center text
- revamp the pages so they look simple, they're also sorted
- adjusted few strings
- improved some behavior, disable capture button on start, etc

Personally I think it's definitely an improvement as it's clearer, so if you like it, **I need your input on PC-98** because when I look at this picture, some keys are on it and not in DOSBOX, vice-versa...

https://commons.wikimedia.org/wiki/File:NEC_PC-9800_series_keyboard.jpg

**Older PC layout:**

dosbox-x_fEngHCMcwa

**Newer PC layout:**

dosbox-x_DTuRNJNPDf

**Older PC-98 layout:**

dosbox-x_6l8H9I7Ole

**Newer PC-98 layout: (not finished)**

dosbox-x_rdKW3tOYiS

### CODE REVIEW

**Comment by rderooy** [comment]
Very nice improvement!

Regarding the PC98 keyboard, could it be that it depends on the model of PC98, similar to how there was a PC XT and AT layout?

Also, should there be a PC XT layout? And how international layouts in PC mode like German QWERTZ, French AZERTY or even Asian layouts like a Japanese keyboard?

**Comment by aybe** [comment]
Here's the final PC98 layout, it's kinda hard to get anything better than that according space constraints:

dosbox-x_dEWebg4vA3

I've also enlarged the modifiers toggles as they were overflowing otherwise.

Haven't been able to find much more regarding JP layout, these are puzzling:

[JP Japanese Keyboard Layout for (NEC PC-9800 on PC98-NX) - Keyboard Layout Info](http://kbdlayout.info/kbdnecat/)

[JP Japanese Keyboard Layout for (NEC PC-9800 Windows 95) - Keyboard Layout Info](http://kbdlayout.info/kbdnec95/)

[JP Japanese Keyboard Layout for (NEC PC-9800) - Keyboard Layout Info](http://kbdlayout.info/kbdnec/)

[JP Japanese NEC PC-9800 Keyboard Layout - Keyboard Layout Info](http://kbdlayout.info/kbdnecnt/)

To answer your question, one would use loadable layouts that the mapper would draw instead.

[kbdedit.com](kbdedit.com) (not free)

ScreenDumpMain

[Keyboard Layout Editor](http://www.keyboard-layout-editor.com/)

chrome_6FNkmm2Io5

Last one is probably best as it's free and online, but IMO the sheer amount of work for the outcome is questionable.

**Comment by aybe** [comment]
I fixed all the errors so that the builds all pass successfully.

Feel to review it when you have a minute and merge it if you like the changes.

Thank you.

**Comment by Wengier** [comment]
@aybe Nice improvements, but if you load a language file such as fr_FR.lng (French) and open the mapper, then you will soon notice problems:

image

Hope you can fix them.

**Comment by aybe** [comment]
Good catch! See #3518 for fix and slightly improved layout.

**Pull request merged**
