### PR TITLE
Misc bug fixes

### PR DESCRIPTION
**Pull request by Shane32**
- validation check in el-torito mounting bug fix
- assignment in IDE_Auto for 3rd and 4th drive (which was never used since BIOS currently only supports 2 HDDs)
- ensure checks against imageDiskList to use MAX_DISK_IMAGES
- ramdrive formatting minimum size check validation update

### CODE REVIEW

**Comment by Shane32** [comment]
- log message cleanup in the ramdrive formatting code

**Comment by Shane32** [comment]
- Print success message when mounting el torito floppy image from cdrom

**Comment by Shane32** [comment]
the imageDisk name is only used in swapInDisks, but it IS a public member....

**Comment by Shane32** [comment]
Pushed potential fix for #593 ---- added checking for failure to open files when -fs none

**Comment by joncampbell123** [comment]
Nice!

Perhaps the message name could be PROGRAM_MOUNT_STATUS_ELTORITO instead of PROGRAM_MOUNT_STATUS_2 in the near future?

**Pull request merged**
