### PR TITLE
acinclude: Enable SDL2 by default

### PR DESCRIPTION
**Pull request by Jookia**
This sets configure to have --enable-sdl2 enabled by default

## What issue(s) does this PR address?

Issues like #3433 show that having SDL2 installed isn't enough for configure to build with it, --enable-sdl2 needs to be set by default too.

## Does this PR introduce new feature(s)?

No

## Does this PR introduce any breaking change(s)?

Yes: Builds now use SDL2 by default. This breaks every non-SDL2 build script.
However, this is not my doing: The code in configure.ac prefers SDL2 if it is available already, this just enables finding SDL2.

I'm putting this PR in draft status to figure out what to do about that. @joncampbell123 and @Wengier have experience with building the actual application so I'd really enjoy the feedback.

It might be worth flipping things around and disabling SDL1 by default and updating build scripts so they pass --disable-sdl1.

### CODE REVIEW

**Comment by joncampbell123** [comment]
If you change whether SDL2 is default enabled, then the build-debug and build-debug-sdl2 scripts need to be updated so that build-debug still does SDL1.

**Comment by Jookia** [comment]
Is it just the build-* scripts? Aren't there more?

**Comment by joncampbell123** [comment]
No, that's about it. The build scripts and configure.ac.

Your change shouldn't affect the VS2019 project files.

**Comment by Jookia** [comment]
Okay, I've fixed things up, time to see what breaks. :)

**Comment by Jookia** [comment]
Uh I accidentally closed this.

**Comment by Wengier** [comment]
I wonder if it is better to name the option ``--enable-sdl`` as ``--enable-sdl1`` to better reflect that it is for enabling SDL1 instead of SDL in general?

**Comment by Jookia** [comment]
That could be an idea but I don't want to break anyone's build scripts.

**Comment by Jookia** [comment]
Is there an update on this?

**Comment by Jookia** [comment]
Is there any interest in this?

**Comment by joncampbell123** [comment]
Is this no longer a work in progress?

**Comment by Jookia** [comment]
I don't know, nobody's told me what to do next.

**Comment by Jookia** [comment]
I'm going to close this PR for now and later replace it with a different PR later.

**Pull request closed without merging**
