### PR TITLE
Fixes for Haiku OS

### PR DESCRIPTION
**Pull request by amol-**
Provide necessary fixes to make DosBox-X correctly compile and start on Haiku.
There are still some issues to be addressed, but I was able to start and play Warcraft2 on it so it's functional enough to be usable.

### CODE REVIEW

**Comment by Torinde** [comment]
Related to #3537 by @supin96

I wonder about the reverse - can BeOS be booted as guest OS in DOSbox-X?

**Comment by joncampbell123** [comment]
> Related to #3537 by @supin96
> 
> I wonder about the reverse - can BeOS be booted as guest OS in DOSbox-X?

Can BeOS run on a 486, Pentium, Pentium MMX, or Pentium II system? Then it might work in DOSBox-X.

**Comment by rderooy** [comment]
BeOS required a Pentium or better when it came out for x86 in 1998.

**Comment by maron2000** [comment]
Did this PR break MinGW builds?

**Comment by amol-** [comment]
> Did this PR break MinGW builds?

The timing seems to match, but unclear to me how this PR could have caused drive_local.cpp to not get linked and I sadly don't have a MingGW environment I can use for testing.

**Comment by maron2000** [comment]
Sad to inform you that this PR indeed broke MinGW builds.
Build was successful by reverting the changes.
I'm not sure which change broke it.
https://github.com/maron2000/dosbox-x-1/actions/runs/4143183102

**Pull request merged**
