### PR TITLE
Start of integration of DOSBox SVN where DOSBox-X left off

### PR DESCRIPTION
**Pull request by Allofich**
# Description

_Summary of changes brought by this PR._

Integrates the next 3 DOSBox SVN commits starting from where they seem to be missing from DOSBox-X.

**Does this PR address some issue(s) ?**

May be slightly helpful for https://github.com/joncampbell123/dosbox-x/issues/975, as a more common base would probably make any feature integration go more smoothly.

**Additional information**

I was looking at the DOSBox-X code, and it looks like it started on GitHub based on an older SVN base:
https://github.com/joncampbell123/dosbox-x/commit/f3318240311646e6aa14663a9e3e2c41d0da2a68

Then you integrated the daum branch, which included newer commits from mainline:
https://github.com/joncampbell123/dosbox-x/commit/21614b8c3f2e945fb46b0f1bbd3d9f12f7847355

I think this gave you as far as commit r3873 from mainline.
https://sourceforge.net/p/dosbox/code-0/3873/

You have later commits that selectively add in other mainline commits, like this one:
https://github.com/joncampbell123/dosbox-x/commit/85de2c9372bd9201964446e10d93266bc54672c9

I would like to try to help fill in the gaps so that the improvements from mainline DOSBox are also in DOSBox-X.

This PR includes the next 3 commits after r3873, authored by qbix79.

https://sourceforge.net/p/dosbox/code-0/3834/
https://sourceforge.net/p/dosbox/code-0/3835/
https://sourceforge.net/p/dosbox/code-0/3836/

There was no conflict with DOSBox-X work, and DOSBox-X successfully compiled and ran. I'm doing the compilation through AppVeyor compiling with Visual Studio 2017 and running the result on Windows 10, so I'm only able to check those environments.

If you're okay with this, I'm thinking of maybe doing these in sets of 3 commits like this, skipping over those that are already in DOSBox-X, and prioritizing DOSBox-X if there are conflicts.

### CODE REVIEW

**Comment by joncampbell123** [comment]
I appreciate the work!

However I cannot accept commit 83631d7661e88887b854b5133afec78f409ab6eb because it assumes the Windows API. I compile DOSBox-X on Linux and Mac OS X as well, and there are others that compile it for AmigaOS, BeOS, and HaikuOS.

**Comment by joncampbell123** [comment]
To clarify, midiOutGetNumDevs() and midiOutGetDevCaps() are specific to Windows and do not exist anywhere else.

**Comment by Allofich** [comment]
OK, actually going in and modifying the contents is a bit out of my depth. Shall I drop the two midi commits, or would you like to modify them yourself as needed? If we drop, I suggest keeping a list of skipped-over commits from SVN, which I could add to this PR.

**Comment by joncampbell123** [comment]
@Allofich Go ahead and drop the MIDI commits and note that they were dropped. I'm OK with the first commit that corrects typos in the source code.

**Comment by Allofich** [comment]
OK, I did so. I dropped 3835 because it was a preparatory commit for 3836, but I may add it again later if I find another SVN commit that wants to use `midi.h`, which was added by 3835 added.

**Pull request merged**
