### PR TITLE
Dynamic Recompilation for ARM

### PR DESCRIPTION
**Pull request by Daniel-Trevitz**
# Description

Add the dynamic recompilation core from dosbox svn trunk
Do some basic work to add the GUI menu cpu selection.

**Does this PR address some issue(s) ?**

#600, #858 

**Does this PR introduce new feature(s) ?**

Add the dynamic recompilation core from dosbox svn trunk

**Additional information**

Only minimally tested. The game I wanted to work on the RPi3 now does, and it seems to be running too a little too quickly. Tested using Wacky Wheels on RPi3 with SDL2 without X (from ssh onto fb)

### CODE REVIEW

**Comment by joncampbell123** [comment]
Nice! Before I accept the pull request, does the core run anything else in a satisfactory manner on your end?

When I have time I'll pull out my Raspberry Pi 3 and see if the ARM version of this core works.

**Comment by Daniel-Trevitz** [comment]
Just ran Commander Keen 1 for a minute and it seemed fine. Ran "Sky roads" as well without any issues.

**Comment by joncampbell123** [comment]
What about 32-bit protected mode games, like DOOM?

**Comment by Daniel-Trevitz** [comment]
Legality aside, I jsut now grabbed doom95.zip from here: https://www.dosgamesarchive.com/download/doom/
doom95.exe complains that it is a Windows NT executable.

**Comment by joncampbell123** [comment]
No, I mean the original DOOM, for MS-DOS.

I don't expect Windows 3.1 and Windows 95 to run against this core just yet :)

**Comment by sikthehedgehog** [comment]
Because, um, that's a Windows port… You need the DOS version (even the shareware version will do).

That said, Wacky Wheels isn't a 32-bit game? Huh (but then again I never looked into it really)

**Comment by joncampbell123** [comment]
I'm only asking to confirm that basic 16-bit real mode and 32-bit flat protected mode stuff works.

**Comment by Daniel-Trevitz** [comment]
Just ran doom19s.exe (Misunderstood what the 95 meant...) works great.

**Comment by joncampbell123** [comment]
Sound good to me then.

**Comment by joncampbell123** [comment]
Unfortunately for me, the dynrec core just causes DOSBox-X to hang on x86_64 Linux.

**Comment by joncampbell123** [comment]
What configuration did you test this on?

**Comment by Daniel-Trevitz** [comment]
I know extremely little about autoconf - but it looks like C_DYNAMIC_X86 is not the default like it should be for x86.

**Comment by joncampbell123** [comment]
Correct. My primary Linux dev system is x86_64 and C_DYNAMIC_X86 was written for 32-bit targets. It still works well when compiled on 32-bit Windows though.

**Comment by joncampbell123** [comment]
Just to check you're compiling to 32-bit ARM on your Pi 3, right?

It looks like the problem is with the way dynrec handles CPU_Cycles. It writes to the memory address from the generated code. Problem is, it assumes the variable is 32 bits wide. On my x86_64 Linux system, it's 64-bit wide. So when CPU_Cycles goes negative it appears to DOSBox-X instead as a very large integer and the tick never completes.

**Comment by joncampbell123** [comment]
I just made some commits that add "dynamic" to the menu for dynrec, and a hack to the dynrec core that works around the incomplete write to CPU_Cycles, which allows dynrec to (so far) work on my system.

**Comment by joncampbell123** [comment]
Awesome, I can run DOSBox-X with cycles=120000 and Blood runs full framerate.

**Comment by joncampbell123** [comment]
I just got the Windows builds with VS2017 to use the dynrec core when targeting 64-bit Windows, and it works.

**Comment by joncampbell123** [comment]
Anyway, thanks again for porting over the dynrec core, it works very well so far!

**Comment by yksoft1** [comment]
Tried and worked on my MSYS2 mingw-w64 toolchain.

@joncampbell123  If the dynrec from DOSBox SVN is enough fast, would we replace our dynamic_x86 for that even if we are on x86-32?

**Comment by fr500** [comment]
I thought the dynarecs were removed for accuracy.
dynrec x86 is not as fast as dynamic_x86

**Comment by joncampbell123** [comment]
It was removed because it has problems with the way page faults are handled, which can cause problems with 32-bit protected mode games and OSes like Windows 95.

But then enough people complained that I added it back, though with the restriction that by default it defer to the normal core whenever 386 protected mode paging is enabled.

**Comment by fr500** [comment]
Ah! good to know!
The new dynarec seems promising, they even added an AARCH64 emitter recently so it seems quite active, and two weeks ago the x86_64 fixes came.

**Comment by joncampbell123** [comment]
The original way DOSBox SVN handled page faults is to push a page fault frame onto the stack and recurse into another execution loop to handle the page fault. When the page fault returns, it exits the sub-loop and continues where it left off.

That's perfectly fine for DOS games and Windows 3.1

The problem is Windows 95, NT, and Linux, where a page fault is handled in user-space and can be interrupted by the kernel when it decides it's time to switch tasks (to resume handling the page fault when the task is revived). Windows 95 doesn't always return to the task that faulted in the same order it left it, and if another task page faults, then DOSBox will recurse again to handle it.

For example, say Windows 95 is running task A, which page faults (to pull in swap) but the kernel decides instead to switch to task B. Task B during it's run page faults (to pull in swap) but Windows 95 decides to switch to task C. Task C is given it's time, then Windows 95 decides to switch back to task A, which then completes it's page fault handler and returns, causing DOSBox to exit the loop and resume whatever it was doing. Problem is, DOSBox is resuming whatever it was doing for task A in task B. That isn't enough to cause problems usually, though eventually it does cause something to get missed and Windows 95 starts to run a little funny and eventually crash. However this can happen in a way that DOSBox never returns from the sub-loop it spawns, and continues running a sub-loop on another page fault. Left to run long enough this can fill up the stack and crash DOSBox.

In the original DOSBox SVN project the CPU cores were written in such a way that if an instruction was interrupted by a page fault, and Windows 95 task switches during a page fault such that they are completed out of order, the CPU state becomes inconsistent and things in Windows 95 start crashing. One of the first things I did in DOSBox-X around 2013 was fix up the normal core so that CPU state is consistent: it either completes and continues, or a page fault happens and the CPU state is rolled back to what it was when the instruction started. Doing that made Windows 95 a lot more stable in DOSBox-X using the normal core!

**Comment by joncampbell123** [comment]
I made substantial modifications to the normal core to throw a guest page fault as a C++ exception so that the CPU core is interrupted immediately and given to the Normal loop as a page fault to happen. This is the "non recursive page fault" handling I implemented.

It even happens to work with the dynamic core... sort of, at least on Windows. On Linux unfortunately the dynamic core doesn't mesh well with the GCC exception handling frame data, so if a C++ exception is thrown while within dynamic core the C++ runtime acts as if nobody were there to catch it (because it can't trace the stack) and DOSBox-X crashes with an uncaught C++ exception. This is why the code was brought back with the restriction to defer to normal core if 386 paging is enabled. Without 386 paging, no C++ exceptions are thrown and it's safe to use.

**Comment by fr500** [comment]
Yeah I have noticed windows works a lot better on X.
On upstream I get "application stopped working" all the time!

Regarding DYNREC's ARM performance, it's decent, not groundbreaking, games like GTA still struggle on Tegra X1 for instance.

That said it's a lot better than with the normal core. Example (not trying to plug my channel, just excited to see discussion, I have been working on dosbox libretro a lot):
https://www.youtube.com/watch?v=VM8WzYw0tAA

I may try to tackle DOSBox-X libretroization again at some point.

My dosbox fork is not too deep, I try to keep the upstream code untouched as much as I can, but I stumbled in some interfaces that had changed and didn't have enough time to ask last time I tried I don't know much about emulators, I just know about libretro :)

**Pull request merged**
