### PR TITLE
Direct3D and shaders support from forums

### PR DESCRIPTION
**Pull request by alexat**
Direct3D/shaders patch used in gulikoza/daum builds. Good for i.e. using nice xBR scaler shaders.

### CODE REVIEW

**Comment by alexat** [comment]
Please take note, Direct3D SDK paths are hardcoded.

**Comment by joncampbell123** [comment]
Before I accept this, would it be possible to define the Direct3D SDK paths in makefile variables so that users who put the SDK elsewhere can just edit the variables to point at it?

**Comment by alexat** [comment]
Added path to Include/Library paths via proper %DXSDK_DIR% envvar, MS sets it.
Please also note this makes DirectX SDK a requirement. If undesired, it may be made conditional via #define / #ifdef

**Comment by alexat** [comment]
Also added a shader set to use.

**Comment by joncampbell123** [comment]
Ready? I'll merge if so.

Can you provide in your next commit instructions for users who want to #ifdef out the DirectX support if they really want to?

**Comment by alexat** [comment]
Yes, basically ready. I'm now checking if existing config options are enough for disabling it and building without DX SDK.

**Pull request merged**
