### PR TITLE
SVN r4386

### PR DESCRIPTION
**Pull request by Allofich**
https://sourceforge.net/p/dosbox/code-0/4386/

(https://sourceforge.net/p/dosbox/code-0/4385/ is skipped because of some conflicts, as I mentioned in
https://github.com/joncampbell123/dosbox-x/pull/1965)

@joncampbell123 
DOSBox-X has some minor differences in the mpu401.cpp, where it uses `mpu.clock.tempo_rel` (multiplies by it, then divides by 0x40).

The `PIC_AddEvent` in `MPU401_Event`, which is modified by this commit, was using `mpu.clock.tempo_rel`, so I made it still do so in this PR.

But another similar-looking `PIC_AddEvent` that was modified by this commit was not using `mpu.clock.tempo_rel`, so I also kept it that way, but should it use `mpu.clock.tempo_rel`? And, the SVN commit then added one more `PIC_AddEvent`, but should that use `mpu.clock.tempo_rel`? Right now it does not.

### CODE REVIEW

**Comment by joncampbell123** [comment]
If you're referring to mpu401.cpp line 167, then it should probably multiply by tempo_rel and divide by 0x40 in the same way it does on line 574 at the tail end of MPU401_Event().

Where is the additional PIC_AddEvent going to go?

**Comment by joncampbell123** [comment]
Also considering the nature of the patch, I wonder if this will solve some issues with certain demoscene entries and PC-98 games that seem to have trouble detecting the MPU-401 or using it.

There are a handful of MS-DOS demoscene entries in the 1991-1993 time frame that are able to use the MPU-401, but if they do, they hang waiting for some condition at program exit.

**Comment by Allofich** [comment]
>Where is the additional PIC_AddEvent going to go?

The other one is within `MPU401_WriteCommand`, under case 0x95.

I've gone ahead and made all three of the `PIC_AddEvent` calls do a multiply by tempo_rel and divide by 0x40, on the assumption that this is correct.

If the case 0x95 one is different for some reason, I can change it back.

**Comment by Wengier** [comment]
Thanks for merging the code!

**Pull request merged**
