### PR TITLE
Ins key cursor update occurs only during shell

### PR DESCRIPTION
**Pull request by aybe**
Is this the right way ?

No more pass-through when a program runs, does not get restored when program exits, though.

I checked with 6.22 on a VM, it doesn't get restored too.

Funnily, it's the opposite in 6.22, small cursor on OVR, big cursor on INS.

### CODE REVIEW

**Comment by aybe** [comment]
Not sure whether all these should set that boolean ?

http://stanislavs.org/helppc/int_21-0.html
http://stanislavs.org/helppc/int_21-4b.html
http://stanislavs.org/helppc/int_21-4c.html
http://stanislavs.org/helppc/int_21-26.html
http://stanislavs.org/helppc/int_21-31.html

**Comment by joncampbell123** [comment]
I don't really know to be honest.

If you have a working MS-DOS bootdisk, you could boot it up and run DOSKEY to see what DOSKEY does with the flag after each call.

**Comment by joncampbell123** [comment]
A lot of the editing controls at the shell so far resemble MS-DOS command interpreter behavior when DOSKEY is resident.

DOSKEY editing behavior seems consistent across IBM PC and PC-98 MS-DOS.

**Comment by aybe** [comment]
Okay I'll try.

**Comment by aybe** [comment]
That's not what I was looking for in fact, my question was rather:

Do programs only raise 4C or can they raise 00 or 31 when exiting ?

If so then I'd set this boolean too in these places.

**Comment by joncampbell123** [comment]
All three exit paths exist on MS-DOS.

DOS programs can exit with INT 20h, INT 21h AH=0, and INT 21h AH=4Ch, they all work.

**Comment by aybe** [comment]
Alright

**Pull request merged**
