### PR TITLE
Update version number and fix Issue #2168 etc

### PR DESCRIPTION
**Pull request by Wengier**
This updates the version number from 0.83.9 to 0.83.10, and made some fixes such as issue #2168 (Ctrl+C makes a heart symbol) and HX-DOS build. The commands "config -set fullscreen=true" and "config -set fullscreen=false" now turn on and off the full-screen mode respectively, per suggestion in Issue #2159.

### CODE REVIEW

**Comment by Jookia** [comment]
Hard object to the pcaptimeout option. Users shouldn't ever need to configure this. Just set it to 10ms or something on Windows. -1 is an invalid value.

**Comment by Wengier** [comment]
@Jookia A value of -1 seems to mean “non-blocking mode” for Windows, but perhaps only valid for Windows. A value of 3000 may cause freeze when DOSBox-X starts on the Windows system, but it seems to work otherwise. In any case, I think different values are probably needed for different OSes. The pcaptimeout option was added as an advanced config option, not a common option. There is a distinction between them.

**Comment by Jookia** [comment]
Can you provide documentation or an API guarantee of what -1 does?

**Comment by Wengier** [comment]
@Jookia I don't think a timeout value of -1 is part of the official cross-platform APIs, but it appears to be part of the de-facto implementations of Windows-side pcap, so it likely only works for Windows and will cause problems with platforms like macOS. On Windows however, I found that even setting to 10ms may cause noticeably slowdown in the DOS shell (easily checked with  pcaptimeout option), but setting to -1 will work. So I believe -1 may be considered a special case only for the Windows platform.

**Comment by Jookia** [comment]
Hmm. That makes sense, but it seems like a bug in WinPcap. The timeout isn't how long it waits to use pcap, it's how long it waits for a device. I guess it's fine now that it's merged :(

**Comment by Wengier** [comment]
@Jookia For the timeout, I think the description was intended to say how long it waits for a device *for the pcap feature/backend* (in contrast to the coming slirp backend), not how long it waits to use pcap itself. But I agree that the description can be further expanded to make it more clear, and it will definitely come.

**Comment by Jookia** [comment]
Oh yes, I understand that. But -1 still gives you a device instantly, so the device is ready. It just sits around doing nothing for a bit if you specify a timeout?

**Comment by Wengier** [comment]
@Jookia It appears that (despite the cross-platform API) WinPcap interprets -1 as "non-blocking mode", so it will use any data available but will never block. But if I specify a positive timeout it may actually block and cause slowdown. I believe the original NE2000 pcap code was written for Windows, which was why it worked well for Windows since the beginning, but may not necessarily be so for platforms like macOS.

**Comment by Jookia** [comment]
Okay, yeah that makes sense. Could you document that in the code since nowhere in the Internet is this explained? Given that it's undefined behaviour basically, having a pcaptimeout option is good is this thing bugs out.

Thanks for that change now that you've explained it. :)

**Comment by Wengier** [comment]
@Jookia Sure! It can be documented in the code to explain why these default values are choosen. Thanks for the suggestion.

**Pull request merged**
