### PR TITLE
Add build instructions for Raspberry PI

### PR DESCRIPTION
**Pull request by maron2000**
Add build instructions for Raspberry PI, which is proven to work by the official Raspberry PI website.

### CODE REVIEW

**Comment by maron2000** [comment]
It's due to security reason that we cannot build it. See the build error.

**Comment by joncampbell123** [comment]
> Why dropping Vista installer support when adding those Pi instructions, how are those related? Or it's just a coincidence in time?
> 
> Is it really needed to drop Vista from the regular installers (I assume that doesn't affect the XP installers)?

I agree. If your pull is about build instructions for the Raspberry Pi, then it should only add build instructions for the Raspberry Pi. Drop the Windows installer commit and I'll merge the Pi instructions.

**Comment by maron2000** [comment]
As per your request, I reverted the commit. Sorry for the confusion.

**Comment by maron2000** [comment]
@Torinde
Let's close this PR by just adding the build instructions for Raspberry PI, as @joncampbell123 requested not to mix several fixes in a single PR.
The website should be updated not now but after the next release.

**Pull request merged**
