### PR TITLE
Maxpat78 patch 2 [wip]

### LINKED ISSUE #4258: Free size limit 2TB not to overflow, 2GB limit to be increased
> 2. when free size is above 2TB, then is reported the difference (e.g. some counter reaches a limit and overflows?)
> 3. when cap is used and cap is above 1919 - only 1919 MB are reported

That is more complicated, seems a design choice. 

GetDiskFreeSpaceEx Win32 API would avoid doing calculations and return directly byte sizes... but in _64-bit_ form: `localDrive::AllocationInfo` wants 16-bit answers, in pure ol' DOS fashion... perhaps something like `fatDrive::AllocationInfo32` should be implemented also in `localdrive::`, but probably your multi-TB drives would need 64-bit integers even in such case.

_Originally posted by @maxpat78 in https://github.com/joncampbell123/dosbox-x/issues/4004#issuecomment-1541717976_
            
For item2:
If there is a limitation due to being "too big for DOS", then it should be one of those?
image

Seeing that DOSbox-X shell shows properly 8GB files (beyond the 4GB max for FAT32), I assume it's possible to show volume sizes beyond 2TB as well. Please consider that it's feasible to have a volume with dozens of TB free space (a few high capacity HDDs in NAS).

In any case if actual free space is above the limit, DOSbox should report the limit instead of overflowing (e.g. 2TB+1byte available should not be reported as 1 byte free).

For item3:
when using a freesize cap I get up to a maximum of 1919 MB. Values above give wrong result of 1919MB:
image

### PR DESCRIPTION
**Pull request by maxpat78**
This patch provides a new GetDiskSize64 member in DOS_Drive, and implements it in localDrive class so that internal shell's DIR command can know proper disk size of a (network) drive >2TB.

## What issue(s) does this PR address?
Fixes #4258 

## Does this PR introduce new feature(s)?

DOS_Drive::GetDiskSize64 
localDrive::GetDiskSize64 

## Does this PR introduce any breaking change(s)?

If yes, describe the breaking change(s) in detail.

## Additional information

Add any additional information here.

### CODE REVIEW

**Comment by Torinde** [comment]
I can't test now, but will do later.

I assume it solves the 2TB overflow, but doesn't solve the "when freesize cap is used and cap is above 1919 - only 1919 MB are reported", correct?

**Comment by maxpat78** [comment]
> I can't test now, but will do later.
> 
> I assume it solves the 2TB overflow, but doesn't solve the "when freesize cap is used and cap is above 1919 - only 1919 MB are reported", correct?

Try it. I didn't test cap nor side effects.

**Comment by joncampbell123** [comment]
> > I can't test now, but will do later.
> > I assume it solves the 2TB overflow, but doesn't solve the "when freesize cap is used and cap is above 1919 - only 1919 MB are reported", correct?
> 
> Try it. I didn't test cap nor side effects.

Both of you: Let me know if it works, then I'll merge it.

**Comment by Torinde** [comment]
1. I get "2 491,17 G Bytes free" - so that works!
2. But the freesize cap is ignored - wrong behavior seems similar to the issue I mentioned in my OP : #2157
3. When booting MS-DOS 7.10 with `convert fat free space = 1147483` (expecting ~1TB) it seems that it overflows:
image

**Comment by joncampbell123** [comment]
Should I merge this or hold it until after release at the end of the month?

**Comment by Torinde** [comment]
IMHO - Hold. Hopefully maxpat78 can look at it after he's done with the more important VHD improvements.

My results:
Item1 is good (improvement). Item3 is unchanged.
Item2 is regression (in Master builds the cap works at least till 1919MB, but here it's ignored?)

**Comment by maxpat78** [comment]
Mmmm... time, yes, to setup a Debian VM and test effects of deeper changes, to accomodate all runtime scenarios!

**Comment by Torinde** [comment]
@maxpat78, any tests I can run to help?

**Comment by maxpat78** [comment]
@Torinde Perhaps I'll find some time to work on this later, I don't think tests can help at this point (I'll have to carry on some tests under Linux, one time or another, to let the fix work outside Windows).
However, if I recall well, your problem originates from some hard-coded value put there to let the full code work (DOSBox-X often set things instead of measure real capacities, i.e. in formatting related interrupts).

**Comment by Lartenik** [comment]
Я сделал перевод en_US  на русский язык ru_RU ,  есть возможно сть адаптировать этот файл для корректной работы программы ?
[ru_RU.txt](https://github.com/joncampbell123/dosbox-x/files/14048994/ru_RU.txt)

**Pull request closed without merging**
