### PR TITLE
Mention synth is for FluidSynth in config file, and fix disk swap counting bug in all cases

### PR DESCRIPTION
**Pull request by Wengier**
Hopefully this is my last pull request this month. I have edited the dosbox-x config file to mention that "synth" is FluidSynth (as discussed in Issue #1497). Also, it should completely fix the disk swap counting bug (#1495) when the internal DOS is rebooted in a different way than using the RE-DOS command. Finally, I changed the remaining "DOSBox" in the dosbox-x config file to "DOSBox-X".

### CODE REVIEW

**Comment by joncampbell123** [comment]
Heads up this month, I'm not going to be able to provide VS2019-compiled binaries this month because of some bizarre hangup with Microsoft's C++ compiler and the xBRZ code that causes meaningless complaints about "4GB something OBJ file". The only Windows binaries this month will be compiled with MinGW.

**Comment by Wengier** [comment]
@joncampbell123 I have always been using VS2015 to compile DOSBox-X, and it compiles the code well so far. Perhaps I can provide a VS2015-compiled Windows binary using the latest code for the release alongside the MinGW version? Or if you still prefer a VS2019-compiled Windows binary over a VS2015-compiled one, @emendelson can still do it because he is using VS2019 16.4.5 which does not have the said problem.

**Comment by joncampbell123** [comment]
That would work. I will credit in the release changelog whoever provides binaries. Can @emendelson or you provide the ARM / ARM64 binaries as well?

Another option I'm about to try, since it's the xBRZ code it's choking on here, is just building VS2019 without XBRZ scaler support this month.

**Comment by joncampbell123** [comment]
Here is the message for reference:

1>------ Skipped Build: Project: SDL, Configuration: Release Win32 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: zlib, Configuration: Release SDL2 Win32 ------
3>------ Skipped Build: Project: SDLmain, Configuration: Release Win32 ------
3>Project not selected to build for this solution configuration 
4>------ Build started: Project: libpdcurses, Configuration: Release SDL2 Win32 ------
5>------ Build started: Project: SDL2, Configuration: Release SDL2 Win32 ------
6>------ Build started: Project: SDL2main, Configuration: Release SDL2 Win32 ------
7>------ Build started: Project: freetype, Configuration: Release SDL2 Win32 ------
8>------ Skipped Build: Project: SDL_net, Configuration: Release Win32 ------
8>Project not selected to build for this solution configuration 
2>adler32.c
4>addch.c
4>addchstr.c
4>addstr.c
4>attr.c
4>beep.c
4>bkgd.c
4>border.c
4>clear.c
2>compress.c
2>crc32.c
2>deflate.c
2>gzclose.c
2>gzlib.c
2>gzread.c
2>gzwrite.c
6>SDL_windows_main.c
5>SDL_atomic.c
5>SDL_spinlock.c
5>SDL_directsound.c
5>SDL_diskaudio.c
5>SDL_dummyaudio.c
5>SDL_audio.c
5>SDL_audiocvt.c
5>SDL_audiodev.c
7>autofit.c
7>ftbase.c
7>ftbbox.c
7>ftbdf.c
7>ftbitmap.c
7>ftcid.c
7>ftfstype.c
7>ftgasp.c
5>SDL_audiotypecvt.c
7>ftglyph.c
4>color.c
2>infback.c
5>SDL_mixer.c
2>inffast.c
4>debug.c
7>ftgxval.c
5>SDL_wave.c
7>ftinit.c
4>delch.c
2>inflate.c
5>SDL_winmm.c
4>deleteln.c
4>deprec.c
7>ftmm.c
5>SDL_wasapi.c
5>SDL_wasapi_win32.c
5>SDL_windows.c
4>getch.c
4>getstr.c
4>getyx.c
5>SDL_xinput.c
2>inftrees.c
2>trees.c
2>uncompr.c
2>zutil.c
7>ftotval.c
7>ftpatent.c
7>ftpfr.c
7>ftstroke.c
7>ftsynth.c
5>SDL_cpuinfo.c
5>SDL_dynapi.c
5>SDL_clipboardevents.c
4>inch.c
7>ftsystem.c
4>inchstr.c
4>initscr.c
4>insch.c
4>inopts.c
4>insstr.c
4>instr.c
4>kernel.c
7>fttype1.c
5>SDL_displayevents.c
5>SDL_dropevents.c
5>SDL_events.c
7>ftwinfnt.c
7>bdf.c
7>ftcache.c
7>cff.c
7>type1cid.c
5>SDL_gesture.c
4>keyname.c
4>mouse.c
4>move.c
4>outopts.c
4>overlay.c
4>pad.c
4>panel.c
5>SDL_keyboard.c
5>SDL_mouse.c
5>SDL_quit.c
7>ftgzip.c
7>ftlzw.c
7>pcf.c
4>printw.c
7>pfr.c
5>SDL_touch.c
5>SDL_windowevents.c
4>refresh.c
4>scanw.c
4>scroll.c
4>scr_dump.c
5>SDL_rwops.c
7>psaux.c
4>slk.c
4>termattr.c
7>pshinter.c
7>psmodule.c
7>raster.c
5>SDL_sysfilesystem.c
4>terminfo.c
4>touch.c
4>util.c
5>SDL_dinputhaptic.c
5>SDL_haptic.c
5>SDL_windowshaptic.c
7>sfnt.c
7>smooth.c
7>truetype.c
7>type1.c
5>SDL_xinputhaptic.c
5>hid.c
4>window.c
5>SDL_hidapijoystick.c
4>pdcclip.c
5>SDL_hidapi_ps4.c
5>SDL_hidapi_switch.c
7>type42.c
4>pdcdisp.c
7>winfnt.c
4>pdcgetsc.c
4>pdckbd.c
7>ftdebug.c
4>pdcscrn.c
4>pdcsetsc.c
4>pdcutil.c
5>SDL_hidapi_xbox360.c
5>SDL_hidapi_xboxone.c
5>SDL_gamecontroller.c
5>SDL_joystick.c
5>SDL_dinputjoystick.c
5>SDL_mmjoystick.c
5>SDL_windowsjoystick.c
5>SDL_xinputjoystick.c
5>e_atan2.c
5>e_exp.c
5>e_fmod.c
5>e_log.c
5>e_log10.c
6>SDLmain.vcxproj -> C:\Users\jon\source\repos\dosbox-x\vs2015\..\obj\SDL2main\Win32\Release SDL2\SDL2main.lib
5>e_pow.c
5>e_rem_pio2.c
5>e_sqrt.c
5>k_cos.c
5>k_rem_pio2.c
5>k_sin.c
2>zlib.vcxproj -> C:\Users\jon\source\repos\dosbox-x\vs2015\..\obj\zlib\Win32\Release SDL2\zlib.lib
9>------ Build started: Project: libpng, Configuration: Release SDL2 Win32 ------
5>k_tan.c
5>s_atan.c
5>s_copysign.c
5>s_cos.c
5>s_fabs.c
5>s_floor.c
5>s_scalbn.c
5>s_sin.c
5>s_tan.c
5>SDL_sysloadso.c
5>SDL_power.c
5>SDL_syspower.c
5>SDL_shaders_d3d11.c
5>SDL_render_d3d.c
5>SDL_render_d3d11.c
5>SDL_shaders_d3d.c
5>SDL_render_gl.c
5>SDL_shaders_gl.c
5>SDL_render_gles2.c
5>SDL_shaders_gles2.c
5>SDL_d3dmath.c
5>SDL_render.c
5>SDL_yuv_sw.c
5>SDL_blendfillrect.c
5>SDL_blendline.c
5>SDL_blendpoint.c
5>SDL_drawline.c
5>SDL_drawpoint.c
9>png.c
5>SDL_render_sw.c
5>SDL_rotate.c
5>SDL.c
5>SDL_assert.c
5>SDL_dataqueue.c
5>SDL_error.c
5>SDL_hints.c
5>SDL_log.c
5>SDL_dummysensor.c
5>SDL_sensor.c
5>SDL_getenv.c
5>SDL_iconv.c
4>libpdcurses.vcxproj -> C:\Users\jon\source\repos\dosbox-x\vs2015\..\obj\libpdcurses\Win32\Release SDL2\libpdcurses.lib
5>SDL_malloc.c
5>SDL_qsort.c
5>SDL_stdlib.c
5>SDL_string.c
5>SDL_syscond.c
5>SDL_thread.c
5>SDL_sysmutex.c
5>SDL_syssem.c
5>SDL_systhread.c
5>SDL_systls.c
5>SDL_timer.c
5>SDL_systimer.c
5>SDL_nullevents.c
5>SDL_nullframebuffer.c
5>SDL_nullvideo.c
5>SDL_blit.c
5>SDL_blit_0.c
5>SDL_blit_1.c
5>SDL_blit_A.c
5>SDL_blit_auto.c
5>SDL_blit_copy.c
5>SDL_blit_N.c
5>SDL_blit_slow.c
5>SDL_bmp.c
5>SDL_clipboard.c
5>SDL_egl.c
5>SDL_fillrect.c
5>SDL_pixels.c
5>SDL_rect.c
5>SDL_RLEaccel.c
5>SDL_shape.c
9>pngerror.c
9>pngget.c
5>SDL_stretch.c
5>SDL_surface.c
5>SDL_video.c
9>pngmem.c
9>pngpread.c
9>pngread.c
9>pngrio.c
9>pngrtran.c
5>SDL_vulkan_utils.c
9>pngrutil.c
9>pngset.c
5>SDL_yuv.c
5>SDL_windowsclipboard.c
9>pngtrans.c
5>SDL_windowsevents.c
9>pngwio.c
9>pngwrite.c
5>SDL_windowsframebuffer.c
9>pngwtran.c
9>pngwutil.c
5>SDL_windowskeyboard.c
5>SDL_windowsmessagebox.c
5>SDL_windowsmodes.c
5>SDL_windowsmouse.c
5>SDL_windowsopengl.c
5>SDL_windowsopengles.c
7>freetype.vcxproj -> C:\Users\jon\source\repos\dosbox-x\vs2015\..\obj\freetype\Win32\Release SDL2\freetype.lib
5>SDL_windowsshape.c
5>SDL_windowsvideo.c
5>SDL_windowsvulkan.c
5>SDL_windowswindow.c
5>yuv_rgb.c
9>libpng.vcxproj -> C:\Users\jon\source\repos\dosbox-x\vs2015\..\obj\libpng\Win32\Release SDL2\libpng.lib
5>SDL.vcxproj -> C:\Users\jon\source\repos\dosbox-x\vs2015\..\obj\SDL2\Win32\Release SDL2\SDL2.lib
10>------ Build started: Project: dosbox-x, Configuration: Release SDL2 Win32 ------
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>25_com.cpp
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>28_com.cpp
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>50_com.cpp
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>append_exe.cpp
10>buffers_com.cpp
10>copy_exe.cpp
10>cwsdpmi_exe.cpp
10>debug_exe.cpp
10>device_com.cpp
10>dos32a_exe.cpp
10>dos4gw_exe.cpp
10>dosidle_exe.cpp
10>dsxmenu_exe_pc.cpp
10>dsxmenu_exe_pc98.cpp
10>edit_com.cpp
10>fcbs_com.cpp
10>find_exe.cpp
10>hexmem16_exe.cpp
10>hexmem32_exe.cpp
10>lastdriv_com.cpp
10>mem_com.cpp
10>move_exe.cpp
10>tree_exe.cpp
10>xcopy_exe.cpp
10>callback.cpp
10>core_dynrec.cpp
10>core_full.cpp
10>core_normal.cpp
10>core_normal_286.cpp
10>core_normal_8086.cpp
10>core_prefetch.cpp
10>core_prefetch_286.cpp
10>core_prefetch_8086.cpp
10>core_simple.cpp
10>cpu.cpp
10>flags.cpp
10>mmx.cpp
10>modrm.cpp
10>paging.cpp
10>debug.cpp
10>debug_disasm.cpp
10>debug_gui.cpp
10>debug_win32.cpp
10>dosbox.cpp
10>cdrom.cpp
10>cdrom_aspi_win32.cpp
10>cdrom_image.cpp
10>cdrom_ioctl_win32.cpp
10>dos.cpp
10>dos_classes.cpp
10>dos_devices.cpp
10>dos_execute.cpp
10>dos_files.cpp
10>dos_ioctl.cpp
10>dos_keyboard_layout.cpp
10>dos_memory.cpp
10>dos_misc.cpp
10>C:\Users\jon\source\repos\dosbox-x\src\dos\dos.cpp(2426,24): warning C4018: '<': signed/unsigned mismatch
10>dos_mscdex.cpp
10>dos_programs.cpp
10>dos_tables.cpp
10>drives.cpp
10>drive_cache.cpp
10>drive_fat.cpp
10>drive_iso.cpp
10>drive_local.cpp
10>drive_virtual.cpp
10>fpu.cpp
10>bitop.cpp
10>bitop self-test disabled for your compiler
10>ptrop.cpp
10>zipfile.cpp
10>8255.cpp
10>C:\Users\jon\source\repos\dosbox-x\src\dos\drive_fat.cpp(527,18): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\dos\drive_fat.cpp(1649,80): warning C4305: 'argument': truncation from 'int' to 'Bit8u'
10>C:\Users\jon\source\repos\dosbox-x\src\dos\drive_fat.cpp(1649,51): warning C4309: 'argument': truncation of constant value
10>fmopl.cpp
10>saa1099.cpp
10>sn76496.cpp
10>ymdeltat.cpp
10>ymf262.cpp
10>printer_redir.cpp
10>pc98.cpp
10>pc98_fm.cpp
10>serialfile.cpp
10>vga_pc98_cg.cpp
10>vga_pc98_crtc.cpp
10>vga_pc98_dac.cpp
10>vga_pc98_egc.cpp
10>vga_pc98_gdc.cpp
10>bios_memdisk.cpp
10>bios_vhd.cpp
10>zmbv.cpp
10>iconvpp.cpp
10>shiftjis.cpp
10>AReverbModel.cpp
10>avi_rw_iobuf.cpp
10>avi_writer.cpp
10>BReverbModel.cpp
10>DelayReverb.cpp
10>File.cpp
10>FileStream.cpp
10>FreeverbModel.cpp
10>allpass.cpp
10>comb.cpp
10>revmodel.cpp
10>guid.cpp
10>ksdataformat.cpp
10>LA32Ramp.cpp
10>LA32WaveGenerator.cpp
10>LegacyWaveGenerator.cpp
10>menu.cpp
10>midi.cpp
10>Part.cpp
10>Partial.cpp
10>PartialManager.cpp
10>Poly.cpp
10>render.cpp
10>render_scalers.cpp
10>riff.cpp
10>riff_wav_writer.cpp
10>ROMInfo.cpp
10>sdlmain.cpp
10>sdl_gui.cpp
10>sdl_mapper.cpp
10>sha1.cpp
10>Synth.cpp
10>Tables.cpp
10>TVA.cpp
10>TVF.cpp
10>TVP.cpp
10>adlib.cpp
10>cmos.cpp
10>dbopl.cpp
10>disney.cpp
10>dma.cpp
10>dongle.cpp
10>floppy.cpp
10>gameblaster.cpp
10>gus.cpp
10>hardopl.cpp
10>hardware.cpp
10>ide.cpp
10>innova.cpp
10>iohandler.cpp
10>ipx.cpp
10>ipxserver.cpp
10>joystick.cpp
10>keyboard.cpp
10>memory.cpp
10>mixer.cpp
10>mpu401.cpp
10>ne2000.cpp
10>nukedopl.cpp
10>opl.cpp
10>directlpt_win32.cpp
10>filelpt.cpp
10>parport.cpp
10>printer.cpp
10>printer_charmaps.cpp
10>pci_bus.cpp
10>pcspeaker.cpp
10>pic.cpp
10>ps1_sound.cpp
10>envelope.cpp
10>extfilt.cpp
10>filter.cpp
10>pot.cpp
10>sid.cpp
10>version.cpp
10>voice.cpp
10>wave.cpp
10>wave6581_PST.cpp
10>wave6581_PS_.cpp
10>wave6581_P_T.cpp
10>wave6581__ST.cpp
10>wave8580_PST.cpp
10>wave8580_PS_.cpp
10>wave8580_P_T.cpp
10>wave8580__ST.cpp
10>sblaster.cpp
10>directserial.cpp
10>libserial.cpp
10>misc_util.cpp
10>nullmodem.cpp
10>serialdummy.cpp
10>seriallog.cpp
10>serialmouse.cpp
10>serialport.cpp
10>softmodem.cpp
10>tandy_sound.cpp
10>timer.cpp
10>vga.cpp
10>vga_attr.cpp
10>vga_crtc.cpp
10>vga_dac.cpp
10>vga_draw.cpp
10>vga_gfx.cpp
10>vga_memory.cpp
10>vga_misc.cpp
10>vga_other.cpp
10>vga_paradise.cpp
10>vga_s3.cpp
10>vga_seq.cpp
10>vga_tseng.cpp
10>vga_xga.cpp
10>voodoo.cpp
10>voodoo_emu.cpp
10>voodoo_interface.cpp
10>voodoo_opengl.cpp
10>voodoo_vogl.cpp
10>bios.cpp
10>bios_disk.cpp
10>bios_keyboard.cpp
10>ems.cpp
10>int10.cpp
10>int10_char.cpp
10>int10_memory.cpp
10>int10_misc.cpp
10>int10_modes.cpp
10>int10_pal.cpp
10>int10_put_pixel.cpp
10>int10_vesa.cpp
10>int10_video_state.cpp
10>int10_vptable.cpp
10>mouse.cpp
10>xms.cpp
10>gui_tk.cpp
10>porttalk.cpp
10>cross.cpp
10>messages.cpp
10>programs.cpp
10>qcow2_disk.cpp
10>regionalloctracking.cpp
10>setup.cpp
10>support.cpp
10>direct3d.cpp
10>hq2x_d3d.cpp
10>ScalingEffect.cpp
10>output_direct3d.cpp
10>output_opengl.cpp
10>output_surface.cpp
10>output_surface_sdl.cpp
10>output_surface_sdl2.cpp
10>output_tools.cpp
10>output_tools_xbrz.cpp
10>shell.cpp
10>shell_batch.cpp
10>shell_cmds.cpp
10>shell_misc.cpp
10>xbrz.cpp
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(611,66): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(612,29): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(617,20): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(635,66): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(636,31): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(641,22): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(652,67): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(653,31): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(658,22): warning C4018: '<': signed/unsigned mismatch
10>C:\Users\jon\source\repos\dosbox-x\src\shell\shell_cmds.cpp(666,67): warning C4018: '<': signed/unsigned mismatch
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>zipcrc.c
10>board26k.c
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>board86.c
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>parts.c
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>keydisp.c
10>adpcmc.c
10>cl : command line warning D9035: option 'QIfist' has been deprecated and will be removed in a future release
10>adpcmg.c
10>fmboard.c
10>fmtimer.c
10>getsmix.c
10>getsnd.c
10>getwave.c
10>opngenc.c
10>opngeng.c
10>pcm86c.c
10>pcm86g.c
10>psggenc.c
10>psggeng.c
10>rhythmc.c
10>sound.c
10>soundrom.c
10>tms3631c.c
10>tms3631g.c
10>dosio.c
10>   Creating library C:\Users\jon\source\repos\dosbox-x\vs2015\..\bin\Win32\Release SDL2\dosbox-x.lib and object C:\Users\jon\source\repos\dosbox-x\vs2015\..\bin\Win32\Release SDL2\dosbox-x.exp
10>Generating code
10>Compiler version has changed, fall back to full compilation.
10>LINK : the 32-bit linker (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\link.exe) ran out of heap space and is going to restart linking with a 64-bit linker
10>LINK : restarting link with 64-bit linker `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x86\link.exe'
10>   Creating library C:\Users\jon\source\repos\dosbox-x\vs2015\..\bin\Win32\Release SDL2\dosbox-x.lib and object C:\Users\jon\source\repos\dosbox-x\vs2015\..\bin\Win32\Release SDL2\dosbox-x.exp
10>Generating code
10>Compiler version has changed, fall back to full compilation.
10>c:\users\jon\source\repos\dosbox-x\src\xbrz\xbrz.cpp : fatal error C1605: compiler limit: object file size cannot exceed 4 GB
10>LINK : fatal error LNK1257: code generation failed
10>Done building project "dosbox-x.vcxproj" -- FAILED.
========== Build: 6 succeeded, 1 failed, 0 up-to-date, 3 skipped ==========

**Comment by joncampbell123** [comment]
Um... I'm humored to see VS2019 throw the same error even if I #ifdef off the entire xbrz.cpp source file.

**Comment by Wengier** [comment]
@joncampbell123 I am building the latest commit a21a255 using VS2015 right now. Since there are 8 projects (including ARM) in total, it will take a while.

**Comment by joncampbell123** [comment]
Cool, thanks. Before you start, I need to make one last commit to update the timestamp.

**Comment by Wengier** [comment]
@joncampbell123 I have tried to build the latest code on all platforms using VS2015, and after I finished Win32 (SDL1 & SDL2), x64 (SDL1 & SDL2), ARM (SDL1 & SDL2), and finally attempted to build for ARM64 too, VS2015 complained that the platform "ARM64" is invalid. I had never tested to build for the ARM platforms before this, and it turns out VS2015 supports ARM but not ARM64 (I checked some websites which seem to confirm this). In any case, I have packaged the dosbox-x.exe program built with VS2015 (executables only) for all platforms except ARM64 below in a Zip file below:

http://cndos.fam.cx/dosware/dosbox-x-windows.zip

**Comment by Wengier** [comment]
@joncampbell123 For the purpose of completeness, I have installed VS2017 on a different computer, and then successfully built the latest code (aa6d356) for the ARM64 platform (SDL1 & SDL2). I also rebuilt for the ARM(32) platform (SDL1 & SDL1) using VS2017. As a result the Win32 & x64 platforms are built with VS2015 whereas ARM & ARM64 platforms are built with VS2017.  The new Zip package containing the dosbox-x.exe program (executables only) for all platforms is now available below:

http://cndos.fam.cx/dosware/dosbox-x-windows-bins.zip

**Comment by Wengier** [comment]
@joncampbell123 Is there other issue(s) I can help?

**Pull request merged**
