### PR TITLE
Fix SYS disk corruption (#1543)

### PR DESCRIPTION
**Pull request by Wengier**
As discussed in Issue #1543, SYS command can disk image corruption on hard drives. So I fixed it. Tested to confirm it works on FAT drives.

### CODE REVIEW

**Comment by joncampbell123** [comment]
Nice! MS-DOS 6.22 SYS.COM works here as well.

**Comment by joncampbell123** [comment]
I was able to complete the work by adding the IOCTL calls needed by FORMAT.COM.

I can now use FORMAT.COM from MS-DOS 6.22 to format a mounted image under the DOSBox-X DOS kernel. That includes the calls made by FORMAT.COM to modify something in the partition table if formatting a hard drive.

The only issue there is that if you use FORMAT /S it will copy COMMAND.COM from drive Z: which is not very useful outside of the DOSBox-X DOS environment. SYS C: however copies the right COMMAND.COM.

**Comment by joncampbell123** [comment]
I'm pretty sure the only thing preventing Windows 95's FORMAT.COM from working so far is the use of the "lock/unlock volume" IOCTLs that the DOS kernel requires you to call before you attempt writing the disk via INT 26h (or else it halts the system with an error message).

Windows 95 OSR2 and later might use entirely different IOCTLs for FAT32, which I don't expect to be implemented anytime soon until FAT32 support is better developed in the FAT driver.

**Comment by Wengier** [comment]
@joncampbell123 FORMAT /S will copy the COMMAND.COM file as specified in %COMSPEC% environment variable. So just specify the correct path for it and it should work as expected.

**Comment by Wengier** [comment]
By the way, why not improve FAT32 support in the FAT driver so that FAT32 disk images can be accessed directly in the DOSBox-X shell as well? FAT32 has arguably become the most important disk format for DOS & Windows 9x/ME in the last two decades.

**Comment by Wengier** [comment]
@joncampbell123 The command "FORMAT A:" using FORMAT.COM from MS-DOS **7.0** already seems to work with the current code (even though LOCK/UNLOCK is already supported in MS-DOS 7.0). But the same command from MS-DOS **7.1** does not work yet. It will call Int21 functions AX=7304h and AX=7305h/CX=FFFFh which are not yet implemented.

**Comment by joncampbell123** [comment]
@Wengier Yup. Those INT 21h calls are the new read/write disk functions, especially for FAT32 drives. http://www.ctyme.com/intr/rb-3229.htm

SYS.COM in Windows 95 does not work yet because it relies on the volume locking functions to work.

**Comment by joncampbell123** [comment]
I think the FAT driver could use a bit of cleanup before fully adding FAT32 since some fundamental changes happened between FAT16 and FAT32.

Besides the obvious change of the FAT table, there is also the root directory which now has it's own allocation chain instead of a fixed area on the disk. The root directory has a starting cluster number.

There are also two "boot sectors" and an extra sector with more info stored in it.

http://hackipedia.org/browse.cgi/Disk%20formats/Filesystems/FAT%2c%20File%20Allocation%20Table%20%28DOS%2c%20Windows%29/Microsoft%20Extensible%20Firmware%20Initiative%20FAT32%20File%20System%20Specification%20%282000%2d12%2d06%29%20v1%2e03%2epdf

(Wow, a "whitepaper" with actual technical documentation in it for once!)

**Comment by Wengier** [comment]
@joncampbell123 SYS.COM from Windows 9x will work fine with the current code if the current reported DOS version is less than 7.0. With a reported DOS version of 7.x, Win9x SYS.COM will work properly if you add a dummy handler for the volume locking functions in dos_ioctl.cpp, e.g.

``case 0x4A:``
``case 0x4B:``
``case 0x6A:``
``case 0x6B:``
``	break;``

Since this code is very simple and I don't really think there are negative effects, perhaps you can add it to the dos_ioctl.cpp file.

**Comment by joncampbell123** [comment]
That would work fine for now.

At some point I should pull out my old MSDN 6.0 / MSVC 6.0 CDs for more documentation on those IOCTLs and their function. Believe it or not back then Microsoft actually bothered to document those IOCTLs in the MSDN library at the time.

**Comment by joncampbell123** [comment]
I think they also documented it in MSVC 4.2's online help, which I also have.

When I find the documentation I'll add comments to the source code to better describe what it all means and how it's supposed to work around those IOCTLs.

**Comment by joncampbell123** [comment]
Windows 98 FORMAT.COM seems to have no problem with formatting if the disk is < 2GB (FAT12 or FAT16 format).

**Comment by Wengier** [comment]
@joncampbell123 I think MS-DOS 7.1/Windows 98 FORMAT.COM will proceed and finish disk formatting as normal,  but when you use DIR again, everything previously on the disk are still there (so the formatting process was completely fake). On the other hand, MS-DOS 7.0 FORMAT.COM does not have this problem (the disk will be empty).

**Comment by joncampbell123** [comment]
Nope. FORMAT.COM from Windows 98 worked correctly here. I tested a 800MB and 1600MB disk image.

**Comment by Wengier** [comment]
Also, "SCANDISK A:" for a floppy image seems to always return the message "ScanDisk cannot examine drive A." and exit. SCANDISK for other drives will work though.

**Comment by Wengier** [comment]
@joncampbell123 The latest code (d61f468) will not compile due to the function definition mismatch in the file dos_program.cpp. Tested with MinGW and VS2015.

**Comment by joncampbell123** [comment]
Another possible thing to consider is that FORMAT.COM generates a new FAT filesystem. One that might not line up with the layout already loaded by the FAT driver. FORMAT.COM calls INT 21h AH=32h to return the DPB, which is always supposed to read the disk to return it.

At some point INT 21h AH=32h in DOSBox-X is going to have to reread the DPB and notify the FAT driver to re-check the BPB and reload the filesystem parameters (and flush caches).

I also checked that FORMAT.COM in Windows 95 and below "format" the hard drive by issuing INT 13h AH=4 VERIFY, not by actually formatting.

**Comment by joncampbell123** [comment]
Second, this was clearly not explained well by RBIL, but the read/write/format/verify IOCTLs use C/H/S values that are relative to the drive partition.

So when FORMAT.COM does a logical read/write of C/H/S 0/0/0, it's reading/writing the boot sector of the partition, not the MBR. This was verified by watching the same FORMAT.COM do it's thing from a Windows 95 bootdisk on an already partitioned hdd image.

**Comment by joncampbell123** [comment]
Checking now.

**Comment by joncampbell123** [comment]
@Wengier What is the error message? It compiles find here.

**Comment by joncampbell123** [comment]
By the way that commit adds the option to MOUNT a local folder to a drive letter and report it as remote so that SCANDISK.EXE doesn't complain about drives mounted like that.

**Comment by joncampbell123** [comment]
@Wengier It turns out Windows 98 FORMAT.COM is using INT AX=7305h, but it never got an error message because of the way INT AX=7303h was implemented, which probably due to bad indentation was never given a break statement or an else return error case (fixing now).

**Comment by Wengier** [comment]
@joncampbell123 The error messages from MSVC are:

Error	C2661	'cdromDrive::cdromDrive': no overloaded function takes 8 arguments	dosbox-x	dos_programs.cpp	224	
Error	C2661	'localDrive::localDrive': no overloaded function takes 6 arguments	dosbox-x	dos_programs.cpp	242	
Error	C2661	'cdromDrive::cdromDrive': no overloaded function takes 8 arguments	dosbox-x	dos_programs.cpp	334	
Error	C2661	'localDrive::localDrive': no overloaded function takes 6 arguments	dosbox-x	dos_programs.cpp	352	

For example in line 224:

newdrive  = new cdromDrive(drive,temp_line.c_str(),sizes[0],bit8size,sizes[2],0,mediaid,error);

There is no new "option" parameter in this code.

**Comment by joncampbell123** [comment]
Heh, if DOSBox-X reports DOS 7.10, SCANDISK.EXE will try to use both INT 25h and INT AX=7305h. Unlike FORMAT.COM though SCANDISK.EXE falls back to INT 25h when INT AX=7305h doesn't work.

**Comment by joncampbell123** [comment]
Ah, that part is Windows only, which is why it doesn't error out here on Linux.

**Comment by joncampbell123** [comment]
Latest commit adds INT AX=7305h, but only if the reported DOS version is 7.10 or higher. Windows 98 FORMAT.COM and SCANDISK.EXE seem happy now.

**Comment by Wengier** [comment]
@joncampbell123 Yes, both FORMAT.COM and SCANDISK.EXE from MS-DOS 7.1/Windows 98 work in the latest commits (except for "SCANDISK A:"). I think right now a few MS-DOS 7.1+ functions are still missing, perhaps they can be properly implemented once FAT32 disk support is improved in the FAT driver.

**Comment by sikthehedgehog** [comment]
Minor nitpick on the convo, but I had to look up to figure out that
you meant INT 21h AX=7305h :P (hey, some BIOS calls take function
numbers too >.>)

**Comment by Wengier** [comment]
@joncampbell123 I have now opened a new issue for direct FAT32 support in Issue #1547.

**Pull request merged**
