### PR TITLE
Support for cues files with MP3/OGG/WAV/FLAC audio tracks

### PR DESCRIPTION
**Pull request by Wengier**
I noticed that both DOSBox ECE and DOSBox-staging support mounting cue files with compressed audio tracks, but DOSBox-X does not yet support this feature. So I decided to port this feature from DOSBox-staging to DOSBox-X so that it is now possible to mount cue files with MP3/OGG/WAV/FLAC audio tracks in DOSBox-X too. Tested to work with both Visual Studio and MinGW.

### CODE REVIEW

**Comment by joncampbell123** [comment]
Looks good! I'll do additional commits to handle any compile failures.

Will a future pull request update the VS2019 project files to enable this?

**Comment by joncampbell123** [comment]
It looks like cdrom_image support just includes the decoders library directly. That's kind of messy, it might be better to compile the decoders library into an .a file and then link to the rest of the program.

**Comment by Wengier** [comment]
@joncampbell123 Yes, for now it includes the decoder library directly to avoid the need of updating the Visual Studio project files (I did not want to modify these files directly since it is possible to cause unexpected issues). But if you prefer, you can surely update the Visual Studio project files to include the library files later.

**Comment by joncampbell123** [comment]
A follow-up on Track 1 repeating the first sector in Windows 95.

The reason it repeats is because Windows 95 periodically sends a command to read sector 16 (command 0x28) even while playing a CD. That read is repositioning playback back to the start.

If I start CD audio playback then use CTRL+ALT+DEL to bring up the Task Manager window (which runs as Win16 and halts all 32-bit processes), CD audio playback proceeds normally.

**Comment by joncampbell123** [comment]
The latest commit makes CD reads fail if a data read is carried out against an audio track. Windows 95 periodically attempts to read data sector 16 in the background for some reason, which according to SCSI MMC standards should immediately fail if playing an audio CD and should fail against non-data sectors. Track 1 can play normally now.

**Pull request merged**
