### PR TITLE
SVN commits

### PR DESCRIPTION
**Pull request by Allofich**
Recent SVN commits

https://sourceforge.net/p/dosbox/code-0/4356/ - Included
https://sourceforge.net/p/dosbox/code-0/4357/ - Skipped because code differs
https://sourceforge.net/p/dosbox/code-0/4358/ - Included
https://sourceforge.net/p/dosbox/code-0/4359/ - Skipped. A fix to mainline from DOSBox-X.
https://sourceforge.net/p/dosbox/code-0/4360/ - Skipped because code differs
https://sourceforge.net/p/dosbox/code-0/4361/ - Included

### CODE REVIEW

**Comment by rderooy** [comment]
@Allofich 

@joncampbell123 keeps track of skipped SVN commits in patch-integration/Skipped SVN commits.txt

**Comment by Allofich** [comment]
That file was made by me, back when I was doing a big merge in of all the SVN commits missing from DOSBox-X that I could. I'm not sure that @joncampbell123 uses it for anything.

**Comment by rderooy** [comment]
@Allofich any chance of porting the OpenGL shaders?

**Comment by Allofich** [comment]
rderooy, I assume it's this commit?

https://sourceforge.net/p/dosbox/code-0/4319/

I tried to port it over. It was going OK at first but I reached a point where there's enough divergence in the existing code that someone who understands the code contents had better do it.

As for the skipped commits file, I'll update it for these commits, but it hasn't been updated for commits between the last one in it (4228) and those of this PR.

**Comment by Wengier** [comment]
@Allofich Are you still working on adding the commits in-between to the file, or you have finished the update for now and will do that later?

**Comment by Allofich** [comment]
Finished for now. I will look at the intervening commits later.

**Comment by Wengier** [comment]
@Allofich and @rderooy I have already added support for GLSL shaders in the latest code by porting that commit. Tested with the shader files "ScanLine.glsl" and "crt-lottes.glsl" (downloaded from: https://github.com/tyrells/dosbox-svn-shaders/tree/master/crt) and seem to work (at least on the SDL1 builds).

**Comment by Wengier** [comment]
@Allofich OpenGL shaders are already supported in both SDL1 and SDL2 builds. If you have difficulty to port other SVN commits similar to this one, please let us know. Thanks!

**Pull request merged**
