### PR TITLE
Fix break keys (Windows SDL1/SDL2)

### PR DESCRIPTION
**Pull request by maron2000**
This PR fixes Ctrl+Pause and Ctrl+Scroll Lock to work as Break key.
Tested on Windows VS builds SDL1/SDL2.

### CODE REVIEW

**Comment by Torinde** [comment]
Per Wikipedia I see the following combinations:
- [SystemRequest](https://en.wikipedia.org/wiki/System_request) = Alt + PrintScreen
- [Break](https://en.wikipedia.org/wiki/Break_key#Modern_keyboards) = Ctrl + ScrollLock
- Pause = Ctrl + NumLock
Pressing the dedicated `Pause` key on 101/102-key keyboards sends the same [scancodes](https://en.wikipedia.org/wiki/Scancode) as pressing `Ctrl`, then `NumLock`, then releasing them in the reverse order would do; additionally, an E1hex prefix is sent
The `Pause` key is different from all other keys in that it sends no scancodes at all on release in PS/2 modes 1 or 2, so it is impossible to determine whether this key is being held down with older devices. In PS/2 mode 3 or USB HID mode, there is a release scancode

I don't see there Ctrl + Pause combination.

**Comment by joncampbell123** [comment]
> Per Wikipedia I see the following combinations:
> 
>     * [SystemRequest](https://en.wikipedia.org/wiki/System_request) = Alt + PrintScreen
> 
>     * [Break](https://en.wikipedia.org/wiki/Break_key#Modern_keyboards) = Ctrl + ScrollLock
> 
>     * Pause = Ctrl + NumLock
>       Pressing the dedicated `Pause` key on 101/102-key keyboards sends the same [scancodes](https://en.wikipedia.org/wiki/Scancode) as pressing `Ctrl`, then `NumLock`, then releasing them in the reverse order would do; additionally, an E1hex prefix is sent
>       The `Pause` key is different from all other keys in that it sends no scancodes at all on release in PS/2 modes 1 or 2, so it is impossible to determine whether this key is being held down with older devices. In PS/2 mode 3 or USB HID mode, there is a release scancode
> 
> 
> I don't see there Ctrl + Pause combination.

Yes, but the OS is not the one sending CTRL + scroll lock, the emulator is responsible for that. Therefore there is no reason to make a special case for CTRL + scroll lock at that code.

Pause becomes CTRL+Break if you hold down CTRL. 
image

**Comment by joncampbell123** [comment]
I appreciate your effort but I don't think this is the right way to go about it.

If Windows builds are having difficulty allowing CTRL+Break and Pause to work, that should be addressed, certainly.

**Comment by maron2000** [comment]
Ok, I'm not strongly sticking to my fix, but sure it has to be fixed.

**Comment by Torinde** [comment]
@maron2000, can you please share where the problem is, how it can be tested?
I myself thought there is problem with Break key, but it transpired the games claiming to use it actually use Scroll Lock :) #4249

Then I see two other issues, but I'm not sure they're related to what you mean: #3582, #3583

**Comment by Torinde** [comment]
When using MORE command - pressing Ctrl+NumLock (equivalent of Pause?) stops it and prints ^C (behavior of Break?), so is Wikipedia is wrong or DOSbox or myself?

image

Ctrl+ScrLock (equivalent of Break), ScrLock, Ctrl, Alt, Shift, Menu, PrtScr, NumLock - don't do anything. Pause - does Pause (e.g. you need to press twice some letter to proceed instead of once).

Not sure if related to the keyboard emulation or to implementation of MORE #4292

**Pull request closed without merging**
