### PR TITLE
Update gameblaster.cpp

### PR DESCRIPTION
**Pull request by RNMB15**
A comment from the patch:

https://sourceforge.net/p/dosbox/code-0/4482/

### CODE REVIEW

**Comment by Allofich** [comment]
It's preferable to have all the relevant code changes together as one commit that builds without error. That way the changes can be more easily examined and, if necessary, the changes can be reverted or tested more easily when trying to isolate where a problem occurred. Also, more descriptive commit messages and an update to the CHANGELOG file should be done. I'll go ahead and put up a PR that does these things. Thanks for drawing attention to the fact that mainline was updated.

**Comment by Allofich** [comment]
Created at https://github.com/joncampbell123/dosbox-x/pull/4072.

**Comment by joncampbell123** [comment]
Please review the check status for most platforms, there is a compile error: https://github.com/joncampbell123/dosbox-x/actions/runs/4399558209/jobs/7704983079#step:5:3695

`gameblaster.cpp:152:19: error: expected primary-expression before 'config'`

Is this patch complete?

**Comment by joncampbell123** [comment]
Wait, did you and @Allofich submit pull requests for the same SVN patch? :laughing: 

Closed as redundant pull of https://github.com/joncampbell123/dosbox-x/pull/4072

**Comment by Allofich** [comment]
Yes I submitted a PR for the same patch because this one was spread out over multiple PRs that didn't individually compile, there wasn't a CHANGELOG entry, etc.

**Pull request closed without merging**
