### PR TITLE
Update zh_TW.lng

### PR DESCRIPTION
**Pull request by 1abcd**
Change some terms
Add more translations to SHELL_CMD_IF_HELP_LONG label

### CODE REVIEW

**Comment by 1abcd** [comment]
@RBTCHENTPE
建議用 .exe 安裝檔，設定中文語言，可以由以下網站下載
https://dosbox-x.com

**Comment by RBTCHENTPE** [comment]
Dear Sir,

Many thanks for your kind reply, I know you are the expert for DosBox in TW.

I hope you could assist me to solve the problems for apply Traditional Chinese ZH_TW on DosBox.

Already 安裝 dosbox0.74, dosbox-x, dosbox-x SDL1, dosbox-x 64bit MinGW SDL2

I have problems to run(SETUP) traditional Chinese ZH_TW. Would you please kindly advise me how to set it up.

1.      The stdfont.15 file is put in the directory of dosbox-x.exe

2.      dosbox-x.conf : as flws

[dosbox]

##  language = TW

language                  = zh_TW

title                     = 

 [dosv]

## dosv       = tw

dosv        = cht

### dosv=off output=ttf font=MingLiu country=886,950

fontxsbcs  = 

##fontxdbcs  = 

getsysfont  = false

fontxdbcs   = stdfont.15

fontxdbcs14 = stdfont.15

gbk        = false

yen        = false

fepcontrol = both

3. Following message for your reference,

Dear Wenyuan,

Thanks a lot for your kindly prompt reply,

1.      I haw press url link zh_TW.lng got html page shown as hereunder:

2.      I select All and copy to clipboard.

3.      Apple note open a new file copy all contents and then save it as zh_TW.lng 

4.      put zh_TW.lng in the directory of dosbox-x.exe

5.     Run dosbox-x SDL2 :

6.     SET config language = zh_TW

7.       Shown the same alert message : “Could not load language message file 'TW' Tdefault language will be used.”

8.      Would you please kindly advise me if I should download the language file of “zh_TW”

9.      

10.  Would you please kindly advise me the download url address of the zh_TW file?

Link zh_TW.lng got html contents parts as follows:

:DOSBOX-X:LANGUAGE:Traditional Chinese

:DOSBOX-X:CODEPAGE:950

:DOSBOX-X:VERSION:0.83.16

:DOSBOX-X:REMARK:建議使用繁體/正體中文DOS/V模式或者TTF輸出選項和字碼頁950配合中文TTF字型以直接支援中文顯示和列印

:AUTOEXEC_CONFIGFILE_HELP

本段落各行指令將在啟動時執行.

你可以把 MOUNT 指令寫在本處.

.

:CONFIGFILE_INTRO

# 這是給 DOSBox-X %s 使用的組態檔案。(敬請用最新版 DOSBox-X)

 

B. Rgds.,

Robert Chen

**Comment by Dobby233Liu** [comment]
@RBTCHENTPE sorry for the misdirection in my previous comment to you, you should set `language` configuration to the full path to the zh_TW.lng you previously downloaded. You should probably open a new issue to not clutter the comment section here.

**Comment by RBTCHENTPE** [comment]
Dear Sir,

I have solved the problems to run traditional Chinese ZH_TW.
1.	The stdfont.15 file is put in the directory of dosbox-x.exe
2.	dosbox-x.conf :
[dosbox]
language = zh_TW.lng ( instead of language = zh_TW )
 [dosv]
dosv = cht
getsysfont  = false
fontxdbcs   = stdfont.15
fontxdbcs14 = stdfont.15

It is workable and there is  no more alert message : “Could not load language message file 'TW' Tdefault language will be used.”

Thanks a lot,

**Comment by RBTCHENTPE** [comment]
Dear Sir,

I have solved the problems to run traditional Chinese ZH_TW.

1.	The stdfont.15 file is put in the directory of dosbox-x.exe
2.	dosbox-x.conf :
[dosbox]
language = zh_TW.lng ( instead of language = zh_TW )
[dosv]
dosv = cht
getsysfont = false
fontxdbcs = stdfont.15
fontxdbcs14 = stdfont.15

It is workable and there is no more alert message : “Could not load language message file 'TW' Tdefault language will be used.”

Thanks a lot,

Robert Chen

**Pull request merged**
