### PR TITLE
Ensure local dosbox.conf is used when current directory is unexpected.

### PR DESCRIPTION
**Pull request by aybe**
## Merge #1351 before

# Description

Local dosbox.conf can be ignored when started with a weird current directory such as SYSTEM32.

**Does this PR address some issue(s) ?**

#1319

**Additional information**

Works but not sure if it was the best place to put it on.

### CODE REVIEW

**Comment by yksoft1** [comment]
Consider another way of using GetFullPathName() as #pragma comment(lib) won't work in MinGW.
By the way, what would this cause when dosbox-x.exe is running in Windows system32 directory in Windows systems with no VirtualStore redirect feature such as Windows XP/2003 or ReactOS?

**Comment by aybe** [comment]
OK, isn't the minimum version Win7?

Le 12 nov. 2019 10:03, yksoft1 <notifications@github.com> a écrit :

Consider another way of using GetFullPathName() as #pragma comment(lib) won't work in MinGW.
By the way, what would this cause when dosbox-x.exe is running in Windows system32 directory in Windows systems with no VirtualStore redirect feature such as Windows XP/2003 or ReactOS?

**Comment by yksoft1** [comment]
If you use my nmakefile (/ref-nmake/) in VS2017 command prompt to build, the executable should work  in XP. Don't know whether VS2019's CRT still support XP.

**Comment by aybe** [comment]
Currently I have moved all projects to VS19 (so I'm getting is not a valid Win32 app in XP) but I think it should be possible to downgrade to the old toolset targetting XP, yet keep a good dev experience on Windows.

When this is done, I'll be able to test, I think with some extra checks it should be possible to accomodate the different scenarios.

**Comment by aybe** [comment]
XP support is back -> #1351

**Comment by aybe** [comment]
@yksoft1
Not sure I understand what you meant ... please explain. If dosbox EXE was effectively in SYSTEM32 then this is virtually a no-op, tested in XP and it just works as usual.

**Comment by yksoft1** [comment]
DOSBox-X, before this commit, always wanted to load dosbox.conf not from EXE directory but from the current directory. I don't know if this was intended or a mistake.

**Comment by joncampbell123** [comment]
I prefer that it load from the current directory, or at least load from the current directory first before checking alongside the EXE

**Comment by aybe** [comment]
Okay, my approach is wrong,

I close, if problem surfaces again someone else will probably solve it with a better fix.

**Pull request closed without merging**
