### PR TITLE
Update website links to the 20230901 release

### PR DESCRIPTION
**Pull request by maron2000**

### CODE REVIEW

**Comment by Torinde** [comment]
I don't see in the code the removal of "Currently unavailable" tooltips - but I assume you removed those somehow?
image

HX DOS link - should you wait for @joncampbell123 to manually upload it as mentioned [here](https://github.com/joncampbell123/dosbox-x/issues/4334#issuecomment-1703999221)?

I see you merged the Vista+ x86 and Win7+ x64 links (as Installer is only one since #4352)... I'll test Vista x64, because previous installer didn't work there (#3943).

**Comment by Torinde** [comment]
Installer works in Vista x64!

**Comment by maron2000** [comment]
@Torinde I don't get your point of the screenshot you showed.
It will be like the picture below.
For the HX-DOS build, we can either wait for the upload or just go ahead. It can be easily updated anyway.
website

**Comment by Torinde** [comment]
Ah, OK!

What about condensing a little bit:

32/64-bit Setup: [XP+](https://dosbox-x.com/XPsetup.exe) | [Vista+](https://dosbox-x.com/Regularsetup.exe)*

**Comment by maron2000** [comment]
Updated.
website

**Comment by Torinde** [comment]
Good. I would've went without the brackets, but OK.

**Pull request merged**
