### PR TITLE
Support for Japanese EGA mode

### PR DESCRIPTION
**Pull request by Wengier**
This adds supports for Japanese EGA mode (a variant of standard EGA mode with Japanese support), by adopting code from the DOSVax fork of @yksoft1. In this mode Japanese characters can be displayed normally with or without the use of TTF fonts. The original DOSVax fork does not provide font files so that jfontsbcs and jfontdbcs options are required to specify other fonts. On the other hand, this PR makes font files fully optional by building-in fonts generated with PC-98 mode's free fonts (though jfontsbcs and jfontdbcs options (now in [render] section) can still be used to specify different fonts). Most (>90%) additions of this PR come from the built-in fonts (coded in jega.h). This may also be another way for SDL drawn menu to support Japanese text.

### CODE REVIEW

**Comment by roytam1** [comment]
> adopting code from the DOSVax fork of @yksoft1

what about incorporating code from https://github.com/nanshiki/DOSVAXJ3 so IBM JEGA(i.e. AX) and Toshiba J-3100 mode can also be used?

**Comment by Wengier** [comment]
> > adopting code from the DOSVax fork of @yksoft1
> 
> what about incorporating code from https://github.com/nanshiki/DOSVAXJ3 so IBM JEGA(i.e. AX) and Toshiba J-3100 mode can also be used?

It definitely looks like an interesting branch. It even ported the LFN and clipboard features from my older DOSBox SVN-lfn branch (although DOSBox-X apparently contains more recent code for these features). I think DOSBox-X can certainly incorporate other code as you mentioned too.

**Comment by joncampbell123** [comment]
Is Japanese EGA mode for IBM PCs or PC-98?
I'm not aware of any EGA hardware for PC-98, though PC-98 has it's own digital RGB TTL video output connection as I understand it.

**Comment by roytam1** [comment]
> Is Japanese EGA mode for IBM PCs or PC-98?

for IBM PCs. see also: https://en.wikipedia.org/wiki/AX_architecture

**Comment by Wengier** [comment]
It is a variant of the regular EGA mode rather than PC-98 mode. The base code of both EGA and JEGA are very similar.

**Comment by Wengier** [comment]
I have added support for Japanese DOS/V mode too, by setting `dosv=jp` in the config file. I think it is definitely desired by DOSBox-X (#100). I saw no earlier discussion about Toshiba J-3100 mode though. I did not add the IME feature because it apparently requires the modification of the SDL library, and the DOSVAXJ3's modification was for SDL1 build only.

**Comment by joncampbell123** [comment]
Did you forget to commit jega.h?

    In file included from dos_devices.cpp:32:
    dev_con.h:25:10: fatal error: jega.h: No such file or directory
       25 | #include "jega.h"

**Comment by Wengier** [comment]
@joncampbell123 The file jega.h was renamed to jega.h. Fixed accordingly.

**Pull request merged**
