### PR TITLE
xBRZ scaler integration and code

### PR DESCRIPTION
**Pull request by alexat**
- Please check SDL2 part
- Requires DirectX SDK
- Requires project file changes (this is raw source)

### CODE REVIEW

**Comment by aybe** [comment]
There are a few (simple) issues I'm going to fix, moving to its own branch.

**Comment by alexat** [comment]
Sure thing :) I hope to learn stuff from what you fix in it :)

**Comment by aybe** [comment]
hmm well, I'm not actually an expert when it comes to DOSBox-X code base, rather, the two issues I'm looking at are the missing field in the struct, and non-tracked xBRZ files in the solutions to get it to compile.

Now it is building,

Jon will be the definitive reviewer since he just knows it !

**Comment by alexat** [comment]
Ouch, I see what you mean. 

render.h, struct scale, bool xBRZ

Sorry for that.

**Comment by joncampbell123** [comment]
Just curious, the xbrz library seems to process pixels in software.

What part of it requires DirectX?

I'm guessing that xBRZ probably needs the whole frame to process at once, and it probably can't do scanline-by-scanline as the other render scalers do?

I see that the library assumes ARGB order, which makes it unsuitable for Mac OS X's weird BGRA format, but should be OK for Linux and Windows.

If it can process without DirectX, it might be a good idea to have the GFX render code render line-by-line to a buffer in RGBA colorspace using the "normal" scaler (to convert to 32-bit) then in GFX_EndUpdate() call on xBRZ to scale to the final SDL surface.

If you can wrangle that out in the xbrz branch, then I'll accept it into the master and development branches.

**Comment by aybe** [comment]
1. I have done the appropriate changes so the VS solution builds and runs,

https://github.com/joncampbell123/dosbox-x/commits/xbrz

Currently Release SDL2 does not build but I've been unable to fix it:
https://stackoverflow.com/questions/39252385/c-linker-error-lnk2005-already-defined-in-sdl

The required configuration:
```
[sdl]
# fullscreen: Start dosbox directly in fullscreen. (Press ALT-Enter to go back)
#     output: What video system to use for output.
#             Possible values: surface, overlay, opengl, openglnb, openglhq, ddraw, direct3d.
fullscreen=true
output=surface

[render]
# scaler: Scaler used to enlarge/enhance low resolution modes. If 'forced' is appended,
#         then the scaler will be used even if the result might not be desired.
#         Possible values: none, normal2x, normal3x, normal4x, normal5x, advmame2x, advmame3x, advinterp2x, advinterp3x, hq2x, hq3x, 2xsai, super2xsai, supereagle, tv2x, tv3x, rgb2x, rgb3x, scan2x, scan3x, hardware_none, hardware2x, hardware3x, hardware4x, hardware5x, xbrz, xbrz_bilinear.
scaler=xbrz
```

2. This https://github.com/joncampbell123/dosbox-x/commit/969f31bef377b758aade82a909053e189787ce3f definitely should be reviewed.

3. While xBRZ is noticeable under the DOS prompt, the effect is barely noticeable on Prince Of Persia, slightly round pixels but nothing like the shots in https://sourceforge.net/projects/xbrz/, could it be because the scaler size is incorrect ?

**Comment by alexat** [comment]
I'll look into (1).
For (2), yes, this definitely should be reviewed.
For (3), I am attaching some screenshots. Does it look like that for you as well? Please tell which resolution you did use so I can look into it.
xbrz_bi_1

**Comment by joncampbell123** [comment]
I haven't compiled it yet on my end, I am making a build now, but the screenshots are impressive.

I've noticed PC-98 games also greatly benefit from these kind of scalers, including 2xsai.

**Comment by alexat** [comment]
>>> What part of it requires DirectX?
Well, now I am looking stupid, but I wrote that based on my build mixed with another patch... No, no part of xBRZ requires DirectX SDK and it perfectly compiles without it.

**Comment by joncampbell123** [comment]
@alexat xBRZ's source code didn't appear to have any DirectX dependencies in it. Mistakes happen.

**Comment by alexat** [comment]
For rendering line by line, it requires exactly four adjacent lines (2 up / 2 down) to be present to process each pixel, and uses parallel task group execution to speed up the process. It processes only changed lines from each render though if these are supplied.

Because scaler output may not match the final resolution, it uses nearest neighbor (xbrz) or bilinear (xbrz_bilinear) upscaling or downscaling to finally fit the image into screen, again applying parallel execution.

**Comment by alexat** [comment]
But indeed I see the idea of making it independent of the surface format.

**Comment by aybe** [comment]
Just as you, 1920*1200:

2018-06-01 22_25_55-greenshot

2018-06-01 22_26_10-greenshot

```
# This is the configuration file for DOSBox 0.82.7. (Please use the latest version of DOSBox)
# Lines starting with a # are comment lines and are ignored by DOSBox.
# They are used to (briefly) document the effect of each option.
# To write out ALL options, use command 'config -all' with -wc or -writeconf options.

[sdl]
# fullscreen: Start dosbox directly in fullscreen. (Press ALT-Enter to go back)
#     output: What video system to use for output.
#             Possible values: surface, overlay, opengl, openglnb, openglhq, ddraw, direct3d.
fullscreen=true
output=surface

[render]
# scaler: Scaler used to enlarge/enhance low resolution modes. If 'forced' is appended,
#         then the scaler will be used even if the result might not be desired.
#         Possible values: none, normal2x, normal3x, normal4x, normal5x, advmame2x, advmame3x, advinterp2x, advinterp3x, hq2x, hq3x, 2xsai, super2xsai, supereagle, tv2x, tv3x, rgb2x, rgb3x, scan2x, scan3x, hardware_none, hardware2x, hardware3x, hardware4x, hardware5x, xbrz, xbrz_bilinear.
scaler=xbrz_bilinear

[joystick]
# joysticktype: Type of joystick to emulate: auto (default), none,
#               2axis (supports two joysticks),
#               4axis (supports one joystick, first joystick used),
#               4axis_2 (supports one joystick, second joystick used),
#               fcs (Thrustmaster), ch (CH Flightstick).
#               none disables joystick emulation.
#               auto chooses emulation depending on real joystick(s).
#               (Remember to reset dosbox's mapperfile if you saved it earlier)
#               Possible values: auto, 2axis, 4axis, 4axis_2, fcs, ch, none.
joysticktype=none

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
mount c .
c:
cd pop
prince
```

By the way, there seems to be a regression, once you go xBRZ there's no turning back, you have to restart dosbox-x to be able to pick another scaler.

Also, do you think it'd be possible to not enforce aspect ?

**Comment by joncampbell123** [comment]
What does it do if you go back, stop drawing?

**Comment by aybe** [comment]
It does absolutely nothing,

Here's the scenario:
- game starts with above config, scaler is in effect
- I do F11+F to switch to windowed mode
- none of the scalers in the menu do something

It just seems to revert to no scaler at all:

2018-06-01 22_35_54-dosbox-x 0 82 7 3000 cyc_ms prince

**Comment by alexat** [comment]
It can be turned back and forth by toggling on/off specific booleans in render and sdl structures on internal config changes, otherwise it will indeed still be running xBRZ. Also incompatible with output mode change.

For aspect, extra lines added by aspect correction affect scaling.

Overall, your 1920x1200 screenshot looks like as if xBRZ is not running at all.

**Comment by joncampbell123** [comment]
It's true that between mode changes and GFX functions there's a lot of global state that is set and reset. Try tracing: GFX_StartUpdate, GFX_SetSize, GFX_EndUpdate.

**Comment by alexat** [comment]
I just though... this (xBRZ looking like no scaler at all) can possibly be a result of surface format incompatibility. By adding call to supportsXBRZ(*sdl.surface->format) and logging the result it can be verified.

**Comment by aybe** [comment]
If you look closely, very light rounding is visible:

2018-06-01 22_41_01-40861885-f4b4e0cc-65ea-11e8-991b-7ab449dc1646 png 1920x1200

But on welcome screen it is clear that it is in effect:

2018-06-01 22_43_17-greenshot

I've put a breakpoint and indeed it is supported in ```supportsXBRZ```.

**Comment by alexat** [comment]
Hm, text mode indeed looks good.

**Comment by alexat** [comment]
If you can, please upload your dosbox.conf, I'll try to reproduce it on clean build tomorrow (it's 23:50 on my side :D).

**Comment by joncampbell123** [comment]
I am not testing xbrz right now, I am compiling the latest release.

**Comment by aybe** [comment]
@alexat 
Here it is [dosbox.conf.zip](https://github.com/joncampbell123/dosbox-x/files/2064078/dosbox.conf.zip).

@joncampbell123 
ok

**Comment by alexat** [comment]
@aybe 
Thanks. Yup, it fails on my build as well, I'll see what's affecting it.

**Comment by aybe** [comment]
@alexat 
alright

@all
mis-understanding on my side, scaler change works after xBRZ but it has to be **forced** (as usual), this brings the topic of why can't DOSBox-X figure out my screen space can handle it ?

**Comment by alexat** [comment]
Ok, found it.

doublescan=false should be enforced on enabling xBRZ. Adding it to config fixes the issue.

**Comment by alexat** [comment]
@aybe 
render.cpp
        vga.draw.doublescan_set = false;
should be added after
    if (render.scale.xBRZ) {
        // xBRZ requirements
        render.aspect = false;

**Comment by joncampbell123** [comment]
@alexat Sorry about that, didn't realize you weren't talking to me.

DOSBox-X by default runs with doublescan=true in order to accurately render the VGA raster sent to display. However that means in 200-line modes (like 320x200) the scaler is given each scanline twice. doublescan=false disables that so the scaler can do a better job.

**Comment by aybe** [comment]
Yes, got it, now it just works as intended, thanks !

**Comment by alexat** [comment]
@ALL 
I've created #749 with some updates to make it work in windowed mode (no aspect correction though), in D3D and OpenGL output modes and with some minor cleanups.

**Pull request merged**
