### PR TITLE
SVN commits

### PR DESCRIPTION
**Pull request by Allofich**
https://sourceforge.net/p/dosbox/code-0/4387 (Skipped due to conflicts)
https://sourceforge.net/p/dosbox/code-0/4388 (Skipped, see comments below)
https://sourceforge.net/p/dosbox/code-0/4389 (Skipped due to conflicts. DOSBox-X already has a fix for the MayDay demo)
https://sourceforge.net/p/dosbox/code-0/4390 (Skipped due to conflicts)
https://sourceforge.net/p/dosbox/code-0/4391 (Skipped, see comments below)
https://sourceforge.net/p/dosbox/code-0/4392
https://sourceforge.net/p/dosbox/code-0/4393
https://sourceforge.net/p/dosbox/code-0/4394 (Undone by 4395)
https://sourceforge.net/p/dosbox/code-0/4395

### CODE REVIEW

**Comment by joncampbell123** [comment]
Regarding SVN r4388, DOSBox-X defines LINUX=1 when compiling for Linux.

If the #if statement is about Linux adding "8" to scancodes (really?) then it needs to be an #ifdef LINUX, not #if !this && !that && !other

**Comment by joncampbell123** [comment]
Also regarding SVN r4391, masking the Gravis Ultrasound peek/poke address to 20 bits on write is in dispute, because we don't yet know whether the card holds all 24 bits and masks on memory access, or holds only the low 20 bits.

Unfortunately that register appears to be write-only, so I can't just do a read/write test to determine that. Playing audio to test it at the hardware level only confirms that the low 20 bits matter at playback.

Masking at write may also make it more difficult to implement future Gravis Ultrasound PnP (AMD InterWave) emulation which supports more than 20 bits of addressing.

**Comment by Allofich** [comment]
OK, I will remove those commits from the PR.

**Comment by Allofich** [comment]
Shoot, I accidentally added an unneeded commit. Hold on.

**Comment by Allofich** [comment]
OK, I removed those two commits, adding notes about why they were skipped to the skipped commits file.

**Pull request merged**
