### PR TITLE
Implement support for slirp-based connections

### PR DESCRIPTION
**Pull request by Jookia**
# Description

This is no longer a WIP but a finished version of #1863 . Sorry for the duplicate PR.

**Does this PR address some issue(s) ?**

See #1863

**Does this PR introduce new feature(s) ?**

This adds support for slirp-based Internet connectivity.

**Are there any breaking changes ?**

None to my knowledge.

**Additional information**

I've tested this on Linux and Windows.

### CODE REVIEW

**Comment by Jookia** [comment]
Force pushed to fix some whitespace issues.

**Comment by Jookia** [comment]
Force pushed to change 'PCAP' to 'pcap' and 'SLIRP' to 'Slirp' in user-visible messages.

**Comment by Wengier** [comment]
@Jookia Thanks for the efforts. I will test it further, but for now I would suggest to rename the config option "pcaptimeout" in [ethernet, pcap] section to "readtimeout" or so. It was previously named "pcaptimeout" in [ne2000] section only to make it clear that it was for pcap, but it is now under [ethernet, pcap] section any way so I think a name like "readtimeout" would be better.

**Comment by Jookia** [comment]
Could you provide some example code on how to do that? I haven't seen
any other config migrations handle things that way.

**Comment by Wengier** [comment]
@Jookia You are right that most existing config migrations do not involve renaming. But there is already an exception in the code which can serve as an example. You may take a look at the file sdlmain.cpp between line 11826 and 11857, which transfers the config option "dos in hma" in [dos] section to "dos=high" or "dos=low" option in [config] section (which emulates config.sys). Not only it renames the config option but actually completely change its form. Please check it out.

**Comment by joncampbell123** [comment]
Let me know when you're ready for me to merge this.

**Comment by Jookia** [comment]
I'll check out the migration code you referenced.

With that fixed, would this be good for merging?
Though you still need to test.

**Comment by Jookia** [comment]
Okay, done that.

**Comment by Jookia** [comment]
Force pushed to clean up ethernet_slirp error messages

**Comment by Jookia** [comment]
Force pushed to add 'ETHERNET:' namespace in ethernet.cpp error output.

Most of these are just quick fixes I'm picking up as I'm working on
porting a condensed version of this patch set to dosbox-staging.

**Comment by Wengier** [comment]
@Jookia More test is desired of course, but since DOSBox-X 0.83.11 was recently released, I think there should be time to clean up for the rest before the next version.

**Comment by Jookia** [comment]
Is there anything you actually want me to do now? Is this getting merged?

**Comment by Wengier** [comment]
@Jookia I think the main purpose of this PR is to get the feature work, assuming we already have the dependency, since the feature has already been worked on for while and also tested by multiple people. But it will be further cleaned up of course before the next release, e.g. I will see the dependency problem can be improved especially for Windows. Getting merged simply means that the feature is already in a production state, but does not mean that it cannot be further improved to make it work better.

**Comment by Jookia** [comment]
I'm confused. Do you want this or not?

**Comment by joncampbell123** [comment]
@Jookia I'll go ahead and merge this if it's good enough to start testing.

**Comment by Jookia** [comment]
It's production ready, all the code is there and I've tested it fairly well.

**Comment by Wengier** [comment]
I noticed that PKG_CHECK_MODULES is not be supported in some environments and will cause the configure script to fail in such cases, so I have been trying to replace it with AC_CHECK_HEADER and AC_CHECK_LIB as with other libs in #2347.

**Comment by Jookia** [comment]
The change there looks good to me at a first glance.

**Comment by Wengier** [comment]
DOSBox-X 0.83.12 that supports the slirp-based connections has been released. It is not yet enabled for the Visual Studio builds, but I hope more work will be done so that these builds will support it as well.

**Comment by rderooy** [comment]
The new flatpak build is also out and has slirp support
https://flathub.org/apps/details/com.dosbox_x.DOSBox-X

**Pull request merged**
