### PR TITLE
Translation files for DOSBox-X

### PR DESCRIPTION
**Pull request by Dalekamistoso**
These are the files needed for spanish language support.

Also I include original "messages.txt" of a clean installation inside with an appropriate name for default as "en_US.lang" in order to be used as basis for translating DOSBox-X to multiple languages (currently the special characters are not supported in dropdown menus but inside DOS are OK).

In order to use it only needs to change the appropiate value in dosbox.conf (language= .\translations\es\es_ES.lng in windows and ./translations/es/es_ES.lng in Linux)

This enhancement is the result of the fixed issues on #2174 and #2173

### CODE REVIEW

**Comment by rderooy** [comment]
Thanks. Just want to mention that English files should be under 'en' and not 'us'.
e.g. en/en_US.lng

That way there can be an en/en_UK.lng file with colour spelled correctly ;-)

**Comment by Dalekamistoso** [comment]
Yes Richard, you are right.

I was in a hurry and I totally forgot to rename before uploading the commit, thanks for noticing it.

I already fixed it :)

> Thanks. Just want to mention that English files should be under 'en' and not 'us'.
> e.g. en/en_US.lng
> 
> That way there can be an en/en_UK.lng file with colour spelled correctly ;-)

**Comment by Wengier** [comment]
@Dalekamistoso This is definitely helpful.

Why you closed it?

**Comment by Dalekamistoso** [comment]
One of my atomated scripts closed it, thanks for your notice!!

I will reopen now

**Pull request merged**
