### PR TITLE
Move Linux packaging files to contrib/linux

### PR DESCRIPTION
**Pull request by rderooy**
# Description
The general idea is to clean up the root directory of the tree
a bit, and to possibly prepare to support flatpak in the future
without adding more files to the root.

Both "make install" and make-rpm.sh worked after these changes.

My idea was also to move src/dosbox.png to contrib/icons/dosbox-x.png
And to move any Windows and macOS specific packaging files to
contrib/windows and contrib/macos respectively, but I will not do the
latter two myself as I cannot test it.

This is also similar to how dosbox-staging has it's tree layout.

If there is no objection, I will however move src/dosbox.png and
update any references to it to point to the new location.

**Additional information**
References to dosbox.png
```
$ fgrep -r dosbox.png *
Makefile.am:	sips -z 16 16    src/dosbox.png    --out src/dosbox.iconset/icon_16x16.png
Makefile.am:	sips -z 32 32    src/dosbox.png    --out src/dosbox.iconset/icon_16x16@2.png
Makefile.am:	sips -z 32 32    src/dosbox.png    --out src/dosbox.iconset/icon_32x32.png
Makefile.am:	install -m 644 src/dosbox.png $(DESTDIR)$(prefix)/share/icons/hicolor/48x48/apps/dosbox-x.png
Makefile.in:	sips -z 16 16    src/dosbox.png    --out src/dosbox.iconset/icon_16x16.png
Makefile.in:	sips -z 32 32    src/dosbox.png    --out src/dosbox.iconset/icon_16x16@2.png
Makefile.in:	sips -z 32 32    src/dosbox.png    --out src/dosbox.iconset/icon_32x32.png
Makefile.in:	install -m 644 src/dosbox.png $(DESTDIR)$(prefix)/share/icons/hicolor/48x48/apps/dosbox-x.png
make-rpm.sh.in:cp -vf src/dosbox.png ~/rpmbuild/SOURCES/dosbox-x.png || exit 1
src/CMakeLists.txt:	"${CMAKE_CURRENT_LIST_DIR}/dosbox.png"
```

### CODE REVIEW

**Comment by Wengier** [comment]
I agree with the general idea. e.g. to somehow clean up the root directory of the source tree.

**Comment by Wengier** [comment]
@rderooy Do you think scripts such as env-gcc-4.8.sh and mts_to_1080p.sh need to be in the root directory, or can be moved to elsewhere?

**Comment by rderooy** [comment]
I would personally think that most scripts can go into a scripts directory.

Also, all those "documentation", "references", "todo", "plans", "experiments", etc, directories should probably be cleaned up and moved under one directory. But I don't know if @joncampbell123 would be too happy about such structural drastic changes :-)

**Comment by Wengier** [comment]
@rderooy By the way, your SVG image looks good, and I have added it to the DOSBox-X homepage (http://dosbox-x.com/).

**Comment by rderooy** [comment]
I'm thinking of moving the following to contrib tomorrow
- src/dosbox.png
- mappings
- shaders

Perhaps you can move the windows-installer to contrib, perhaps simply as contrib/windows ?

**Pull request merged**
