### PR TITLE
Fix with how DOS_Execute allocates memory to comply with the memory a…

### PR DESCRIPTION
**Pull request by cimarronm**
…llocation strategy for UMB...now, it will allocate and execute in UMB if there is enough memory for the minimum allocation of the executable

# Description

Currently, `DOS_Execute` will search for the largest block of memory irregardless of the memory allocation strategy set and as a result will almost never execute anything in upper memory. The environment block will be allocated in UMB but none of the executable. This patch aligns with the behavior of `loadhigh` in DOS which will allocate in the upper memory if there is enough memory for the size of the executable.

**Does this PR address some issue(s) ?**

Should address PR #2558 

Here is an example with snarf (dos screen capture TSR)
_Before Patch_
```
C:\>lh SNARF.EXE

Snarf 2.0 is now installed in memory

C:\>mem /c

Modules using memory below 1 MB:

  Name            Total          Conventional       Upper Memory
  --------  ----------------   ----------------   ----------------
  SYSTEM      28,720   (28K)     28,720   (28K)          0    (0K)
  COMMAND      3,216    (3K)      3,216    (3K)          0    (0K)
  SNARF        3,984    (4K)      3,984    (4K)          0    (0K)
  Free       700,224  (684K)    618,304  (604K)     81,920   (80K)

Memory Type         Total      Used       Free
----------------  --------   --------   --------
Conventional          640K        36K       604K
Upper                  80K         0K        80K
Reserved              304K       304K         0K
Extended (XMS)     15,360K       448K    14,912K
----------------  --------   --------   --------
Total memory       16,384K       788K    15,596K

Total under 1 MB      720K        36K       684K

Total Expanded (EMS)                   15M (15,269,888 bytes)
Free Expanded (EMS)                    15M (15,269,888 bytes)
...
```

_After Patch_
```
C:\>lh SNARF.EXE

Snarf 2.0 is now installed in memory

C:\>mem /c

Modules using memory below 1 MB:

  Name            Total          Conventional       Upper Memory
  --------  ----------------   ----------------   ----------------
  SYSTEM      28,720   (28K)     28,720   (28K)          0    (0K)
  COMMAND      3,216    (3K)      3,216    (3K)          0    (0K)
  SNARF        3,984    (4K)          0    (0K)      3,984    (4K)
  Free       700,224  (684K)    622,288  (608K)     77,936   (76K)

Memory Type         Total      Used       Free
----------------  --------   --------   --------
Conventional          640K        32K       608K
Upper                  80K         4K        76K
Reserved              304K       304K         0K
Extended (XMS)     15,360K       448K    14,912K
----------------  --------   --------   --------
Total memory       16,384K       788K    15,596K

Total under 1 MB      720K        36K       684K

Total Expanded (EMS)                   15M (15,269,888 bytes)
Free Expanded (EMS)                    15M (15,269,888 bytes)
...
```

### CODE REVIEW

**Comment by Wengier** [comment]
@cimarronm Thanks a lot for the patch! I can confirm that LH command can now load programs high with it. For Visual Studio builds though, "std::max" in line 164 of dos_memory.cpp needs to be changed to "max" in order to compile correctly.

Meanwhile, I think it is probably a good idea to add an option to load COMMAND high too, default to "auto" which means "true" if DOS version is at least 7, or "false" otherwise, similar to the "lfn" option for long filename support, because MS-DOS 7.x automatically loads COMMAND high by default, unlike earlier versions of DOS.

**Comment by cimarronm** [comment]
@Wengier can you test the latest with Visual Studio? That's a good idea for COMMAND...I'll add that as well

**Comment by Wengier** [comment]
@cimarronm Thanks for the fix. Yes, the updated code builds on Visual Studio.

**Comment by Wengier** [comment]
@cimarronm Please feel free to add the said option for COMMAND in another PR. Thanks.

**Pull request merged**
