### PR TITLE
ne2000: Trigger pending timers instead of panicing

### PR DESCRIPTION
**Pull request by Jookia**
This fixes the NE2000 panicking during normal operation.

Reported by gogoud on Discord. 
Earlier fix (lacking TX_Event() call) tested by gogoud. Current fix also tested by gogoud. Both okay.

## What issue(s) does this PR address?

None

## Does this PR introduce new feature(s)?

No

## Does this PR introduce any breaking change(s)?

No

## Additional information

Independently fixed a while back by @kcgen in https://github.com/dosbox-staging/dosbox-staging/commit/4a5c3fefb687f54937cf5433ef753fff8b5581a6 on dosbox-staging. My initial fix lacked the NE2000_TX_Event(0); and seemed to work in tests but I copied that from that commit.

### CODE REVIEW

**Comment by kcgen** [comment]
> I copied that from that commit (https://github.com/dosbox-staging/dosbox-staging/commit/4a5c3fefb687f54937cf5433ef753fff8b5581a6)

@Jookia , could you add me as co-author on the commit and share credit in the notes?

I know some projects don't care about this stuff, but we always try to credit any code that we didn't directly author ourselves (if we can figure out it's history):



And in the [release notes](https://dosbox-staging.github.io/v0-78-0/):



regards.

**Comment by Jookia** [comment]
Sure! I do want to just get some clarification:

- What would you like me to put in the commit message?
- Are you sure about this? The code isn't written or tested by you, just semi-designed and semi-debugged as I only copied one of the fixes, not the time change. I don't want to attach your name to something that turns out to be a hack job of it

While I've got you, could you explain why you shortened the timer length in the commit too? Is that just to make it less likely of these events happening?

**Comment by kcgen** [comment]
Here's an example where I used the Chorus and Reverb settings that ScummVM's team tuned.  I applied those the FluidSynth in Staging:

``` text
commit 3066fa08740bd321d7416f2d983bebfbc4c24226
Date:   Wed Sep 30 18:37:17 2020 -0700

    Apply reasonable chorus and reverb settings to FluidSynth
    
    These settings were tuned by ScummVM forum user mrbumpy409
    started in 2012 and where made the project's default settings
    in 2019.
    
    References:
     - https://forums.scummvm.org/viewtopic.php?t=11632
     - https://github.com/scummvm/scummvm/pull/1858
    
    Co-authored-by: mrbumpy409 <mrbumpy409@forums.scummvm.org>
    Co-authored-by: Cameron Cawley <ccawley2011@gmail.com>
    Co-authored-by: kcgen <1557255+kcgen@users.noreply.github.com>
```

> What would you like me to put in the commit message?

Something like your comment in the PR ticket.

Just wording that connect the dots for future maintainers, if further bugs or fixes are discovered (someone could inform both projects, as an example).

> I don't want to attach your name to something that turns out to be a hack job of it (edit: without your informed consent)

It's just giving credit, and your comment will make it clear. And hey - if there's bugs in this, then someone reporting an error might inform both of us, the two last people to add/think about this little chunk of code.  So either of could help.

> While I've got you, could you explain why you shortened the timer length in the commit too? Is that just to make it less likely of these events happening?

That's right :+1:

**Comment by Jookia** [comment]
Alright, I'll do a fix up of the PR tomorrow.

**Comment by Jookia** [comment]
Alright, I've added the co-author stuff and a very long commit message summarising this PR and my thoughts.

**Comment by kcgen** [comment]
Very nicely done, @Jookia!

**Pull request merged**
