### PR TITLE
[DRAFT] Cleaning up the README

### PR DESCRIPTION
**Pull request by aybe**
The goal is to improve the readability of the README.

While it's extremely verbose, it isn't very comfortable to read and scattered at times.

One of the thing that should be addressed are the paragraphs, i.e. jumping lines will help a lot.

Etc, that will take some time so making this as a draft as I've only scratched the surface for now.

To compare the differences, the easiest is probably to look at them side to side:

https://github.com/joncampbell123/dosbox-x/blob/master/README.md

https://github.com/aybe/dosbox-x/blob/readme-cleanup/README.md

Feel free to comment, suggest and so on.

### CODE REVIEW

**Comment by aybe** [comment]
@joncampbell123, @Torinde

Not there yet but looking for some input and adjust accordingly.

I think it's quite important that the reader sees major features at a glance.

With the section summarizing everything in less than one screen, it's already better.

**Comment by Torinde** [comment]
Agree with succinct/bulleted intro - some of the info currently in the intro paragraphs is kind of repeated further down in the respective section.
Maybe intro was written like that initially expecting the main question to be "what's different from DOSbox original?" - and assuming that's not SO relevant question nowadays it makes sense to trim the intro as aybe did refocuing it on "-X features, at a glance".

On the other hand - a person new to DOS emulators may still need some help, e.g. somewhere to be found a feature-comparison table of various forks (original, X, Staging, Core, Pure, [others](https://github.com/dosbox-staging/dosbox-staging/wiki/DOSBox-forks)?) schellingb/dosbox-pure/issues/364. Maybe [Wikipedia](https://en.wikipedia.org/wiki/DOSBox#Forks), [Emugen Wiki](https://emulation.gametechwiki.com/index.php/DOSBox) or #6230 is the place for that...

What I struggle is understanding the meaning of some feature, e.g. what is "overscan"? Would be great if each bullet/term is linked to a place with details (Wiki guide, the .conf description of the setting - is there a way to link to these lines in the source code?, etc.)

Machines/CPUs lists:
- is FM towns emulated? Paragraph further down mentions only a "stub for forking"
- Hercules listed twice?
- MMX instruction set highlighted, but not SSE?

>- Amstrad, AX, Fujitsu FM Towns, NEC PC-9801, NEC PC-9821, IBM PC, IBM PCjr, Tandy.
>- 3dfx Voodoo, Hercules Graphics Card, JEGA, S3 Trio/Virge/Vision, Tseng Labs ET Series.
>- MDA, Hercules, CGA (B/W, CVBS, RGB), EGA, MCGA, VGA, Tandy, VESA extensions.
>- Intel CPUs: 8086, 80186, 286, 386, 486, Pentium [Pro, II, III] + MMX instruction set.

I suggest listing the videocards/machine types by moment in time/relationship:
- IBM PC, IBM PCjr, Tandy, Amstrad; JEGA, AX, NEC PC-9801, NEC PC-9821
- MDA, Hercules, CGA (B/W, CVBS, RGB), EGA, MCGA
- VGA, Tseng Labs ET Series, S3 Trio/Virge/Vision, VESA extensions; 3dfx Voodoo
- Intel CPUs: 8086, 80186, 286, 386, 486, Pentium [Pro, MMX, II, III]

NT experimental support - in the CHANGELOG there were recently mentions of improvements related to WinXP, so maybe that should be reflected:
>Furthermore, ongoing effort brought up experimental support for NT, from 3.X up to 2000.
- Furthermore, ongoing effort brought up experimental support for NT, from 3.X up to XP.

That will be consistent with the current paragraph in the "Features unlikely to be supported". Also it makes perfect sense to stop at XP (e.g. 2000 and XP are quite similar, Vista is quite different, XP/ME are partially "contemporary")

**Comment by Torinde** [comment]
Tangentially related - add website link in the Github About details - like that:
image
@joncampbell123 , maybe also some relevant "tags" can be added.

**Comment by Torinde** [comment]
Why closing, @aybe?

**Comment by aybe** [comment]
Simply don’t have the time to do it.

**Pull request closed without merging**
