### PR TITLE
Convert mouse wheel movements to (arrow) keys + mapper file reloadable

### PR DESCRIPTION
**Pull request by Wengier**
I have added two new features to DOSBox-X as follows:

1. Mouse wheel movements can now be automatically converted to key presses, configurable by a new option "mouse_wheel_key", which is disabled by default. When set to 1, mouse wheel movements will be converted to up/down arrows. Setting to 2 or 3 will convert such movements to left/right arrows or PageUp/PageDown keys respectively. For now this feature is only available in Windows.

2. Reloading the keyboard mapper file is now possible with the config -set command. Originally a feature of DOSBox-staging, it is now ported to work in DOSBox-X too.

There are some other small cleanups including fixing the error message for Linux when mounting FAT32 drives as mentioned in the discussion of pull request #1656.

### CODE REVIEW

**Comment by Wengier** [comment]
I have extended the mouse wheel movements to (arrow) keys conversion feature to work on non-Windows systems too. It has been tested to work in Linux as well.

**Comment by Wengier** [comment]
The mouse wheel movements to (arrow) keys conversion feature is currently disabled by default, but if it turns out to be very useful, I can make it enabled by default.

**Comment by Wengier** [comment]
I have added the "Boot from disk image" menu item (A:, C:, and D: drives only) in the "Drive" menu to boot the specified disk image directly (Windows only).

**Comment by joncampbell123** [comment]
@Wengier There's a merge conflict with dos_programs.cpp, which one is correct?

**Comment by rderooy** [comment]
He changes the flow of the MFM detection a bit around. And also changes the Bit16u pe1_size to a Bitu, while I had changed it to a Bit32u, as it is stored in 4 bytes in the header. This will just cause it to use 64bits on a 64bits arch which is unnecessary.

Pretty much all the code in DOSBox where Bitu is used, could be changed to Bit32u, as it compiles and works on 32bit.

**Comment by Wengier** [comment]
@rderooy I had to update the flow of that detection code because as I mentioned in the discussion of your pull request #1652, your previous change made my 2GB disk image no longer auto-detectable. It is however auto-detectable with the new code. I have further updated the code to use Bit32u on the other hand.

**Comment by Wengier** [comment]
@joncampbell123 Please use the version with the following code. Thanks!

        Bit32u pe1_size = host_readd(&buf[0x1ca]);
        if ((Bit32u)host_readd(&buf[0x1fa]) != 0) {		// DOS 2.0-3.21 partition table
            pe1_size = host_readd(&buf[0x1fa]);
            starthead = buf[0x1ef];
            startsect = (buf[0x1f0] & 0x3fu) - 1u;
            startcyl = (unsigned char)buf[0x1f1] | (unsigned int)((buf[0x1f0] & 0xc0) << 2u);
            endcyl = (unsigned char)buf[0x1f5] | (unsigned int)((buf[0x1f4] & 0xc0) << 2u);
            ptype = buf[0x1f2];
            heads = buf[0x1f3] + 1u;
            sectors = buf[0x1f4] & 0x3fu;
        } else if (pe1_size != 0) {						// DOS 3.3+ partition table, starting at 0x1BE
            starthead = buf[0x1bf];
            startsect = (buf[0x1c0] & 0x3fu) - 1u;
            startcyl = (unsigned char)buf[0x1c1] | (unsigned int)((buf[0x1c0] & 0xc0) << 2u);
            endcyl = (unsigned char)buf[0x1c5] | (unsigned int)((buf[0x1c4] & 0xc0) << 2u);
            ptype = buf[0x1c2];
            heads = buf[0x1c3] + 1u;
            sectors = buf[0x1c4] & 0x3fu;
        }

**Comment by Wengier** [comment]
@joncampbell123 In other words, please select the first version for both of the following:

```
<<<<<<< master
        Bit32u pe1_size = host_readd(&buf[0x1ca]);
        if ((Bit32u)host_readd(&buf[0x1fa]) != 0) {		// DOS 2.0-3.21 partition table
            pe1_size = host_readd(&buf[0x1fa]);
=======
        Bit32u pe1_size = host_readd(&buf[0x1fa]); // number of sectors in partition
        if (pe1_size != 0) {     // DOS 2.0-3.21 partition table, starting at 0x1EE
>>>>>>> master
            starthead = buf[0x1ef];
            startsect = (buf[0x1f0] & 0x3fu) - 1u;
            startcyl = (unsigned char)buf[0x1f1] | (unsigned int)((buf[0x1f0] & 0xc0) << 2u);
            endcyl = (unsigned char)buf[0x1f5] | (unsigned int)((buf[0x1f4] & 0xc0) << 2u);
            ptype = buf[0x1f2];
            heads = buf[0x1f3] + 1u;
            sectors = buf[0x1f4] & 0x3fu;
<<<<<<< master
        } else if (pe1_size != 0) {						// DOS 3.3+ partition table, starting at 0x1BE
            starthead = buf[0x1bf];
            startsect = (buf[0x1c0] & 0x3fu) - 1u;
            startcyl = (unsigned char)buf[0x1c1] | (unsigned int)((buf[0x1c0] & 0xc0) << 2u);
            endcyl = (unsigned char)buf[0x1c5] | (unsigned int)((buf[0x1c4] & 0xc0) << 2u);
            ptype = buf[0x1c2];
            heads = buf[0x1c3] + 1u;
            sectors = buf[0x1c4] & 0x3fu;
=======
        } else {                 // DOS 3.3+ partition table, starting at 0x1BE
            pe1_size = host_readd(&buf[0x1ca]);
            if (pe1_size != 0) {
                starthead = buf[0x1bf];
                startsect = (buf[0x1c0] & 0x3fu) - 1u;
                startcyl = (unsigned char)buf[0x1c1] | (unsigned int)((buf[0x1c0] & 0xc0) << 2u);
                endcyl = (unsigned char)buf[0x1c5] | (unsigned int)((buf[0x1c4] & 0xc0) << 2u);
                ptype = buf[0x1c2];
                heads = buf[0x1c3] + 1u;
                sectors = buf[0x1c4] & 0x3fu;
            }
>>>>>>> master
```

**Comment by Wengier** [comment]
I have tried to resolve the merge conflict myself by using the "Resolve conflicts" button, but unfortunately the "Commit merge" button does not work from my end. So I think only @joncampbell123 can do it in this case.

**Comment by joncampbell123** [comment]
This is going to take a little work, Github merging seems a bit confused.

**Pull request merged**
