### PR TITLE
Mapper GUI adjustments

### PR DESCRIPTION
**Pull request by aybe**
Changes:

- ensure text doesn't overflow in buttons as well as captions, trim and add ellipsis if it's the case
- give slightly more space to add/del/next to try prevent ellipsis
- slightly move pages to the right so it looks aligned overall
- enlarge host button so it looks aligned with the rest
- rework non-Western stuff layout

dosbox-x_rKpLHXBIZK

dosbox-x_68iN1GxlD4

### CODE REVIEW

**Comment by Wengier** [comment]
I have a question: for "Previous pages" and "next pages" buttons, do you want to use "<-" and "->" for all languages, or still use native-language messages? I tried to use the former in my PR #3517 in response to your previous PR #3514.

**Comment by aybe** [comment]
Honestly, until you talked about other languages, I haven't thought about that aspect at all.

These were overflowing with the changes I've done and decided to simply use arrows.

I guess arrows are an universally understood symbol, maybe it's best to only use them, makes things even simpler.

**Comment by Wengier** [comment]
@aybe I agree with the approach to use arrows, which is why I tried to remove native messages for them altogether in my PR #3517. But we need to make sure there are no conflicts in the two PRs. If you like, you can come to the DOSBox-X Discord channel for real-time discussions.

**Comment by Wengier** [comment]
FYI I did not make much change to sdl_mapper.cpp file really, but basically ones related to MSG_Get("PREVIOUS_PAGE") and MSG_Get("NEXT_PAGE"), as seen in the screenshot below:

IMG_0532

Perhaps you can include the MSG_Get changes in this PR, and I will then remove changes to the sdl_mapper.cpp file in my PR completely.

**Comment by aybe** [comment]
There you go: https://github.com/joncampbell123/dosbox-x/pull/3518/commits/d427dedd8c56c86e4531d98b7a45a5c459cc12fa.

**Comment by Wengier** [comment]
@aybe Nice. Removed changes to sdl_mapper.cpp in my PR too.

**Comment by Wengier** [comment]
FYI The build issue with HX-DOS builds are not caused by this PR, but due to the recent IDE change by @joncampbell123 in the repository code. I have already fixed this in my said PR.

**Comment by aybe** [comment]
@Wengier nice 😃

**Pull request merged**
