### PR TITLE
Update flatpak support

### PR DESCRIPTION
**Pull request by rderooy**
# Description
- Updated tinyfiledialog to make it work in flatpak
- updates to the metainfo.xml file

Right now tinyfiledialog does not work in flatpak, I have worked with the developer and this updated version fixes the incompatibility issues.

### CODE REVIEW

**Comment by Wengier** [comment]
@rderooy There seems to be unsolved conflict in the file src/libs/tinyfiledialogs/tinyfiledialogs.c. Could you check it? Thanks.

**Comment by rderooy** [comment]
strange. there was no conflict before.

**Comment by rderooy** [comment]
ok, found it. You just merged a PR from @Allofich https://github.com/joncampbell123/dosbox-x/commit/d444e2924813430fe384ba90b5d71a8625854c4a which changed tinyfiledialog.c which broke it.

**Comment by Wengier** [comment]
Right, there is no conflict now.

**Pull request merged**
