### PR TITLE
SVN commits

### PR DESCRIPTION
**Pull request by Allofich**
https://sourceforge.net/p/dosbox/code-0/4331 - In this PR
https://sourceforge.net/p/dosbox/code-0/4332 - In this PR
https://sourceforge.net/p/dosbox/code-0/4333 - Already in DOSBox-X
https://sourceforge.net/p/dosbox/code-0/4334 - Conflict
https://sourceforge.net/p/dosbox/code-0/4335 - Conflict
https://sourceforge.net/p/dosbox/code-0/4336 - In this PR

### CODE REVIEW

**Comment by Wengier** [comment]
@Allofich I think only SVN r4336 is mentioned in CHANGELOG, but not any other commits?

**Comment by Allofich** [comment]
That's because it's the only one with a change of significance to the end-user. That's how I've handled adding SVN commits to the changelog so far, because many SVN commits are just formatting changes with little or no effect on the end-user. I have not recorded every SVN commit number in my PRs, such as when they are just code cleanup, fixing warnings, fixing misspellings, or have unclear commit messages.

For checking whether a particular commit has been merged in, probably the best way is to search for that commit number (r####) in the codebase through GitHub, as I've always been sure to include it in the commit messages and PR comments.

**Comment by joncampbell123** [comment]
@Allofich SVN commits look good, there's a conflict in CHANGELOG that needs to be resolved before I can merge.

**Comment by Allofich** [comment]
Fixed.

@Wengier, thanks for adding in SVN r4330 to the changelog.

**Comment by Allofich** [comment]
Did some cleanup (was having trouble with an unwanted line-end change in the CHANGELOG file) which was why I did force-pushes. I'm done with it now.

**Pull request merged**
