### PR TITLE
Fix hanging on Windows RT, block dynarec on RT 8.x

### LINKED ISSUE #1418: Hang on startup on Windows RT/Windows 10 ARM32
**Describe the bug**
It hangs on startup, leaving a blank screen with a cursor. 
Sometimes the welcome screen does show up, but hangs shortly afterwards.
The following log show repeatedly in the console:
```
CPU: Illegal/Unhandled Interrupt Called 6
```

**To Reproduce**
Just start dosbox-x.

**Expected behavior**
It should run as normal.

**Screenshots**

**Environment (please complete the following information):**
 - Operating system
Windows RT, or Windows 10 ARM, running the 32-bit ARM build
 - DOSBox-X release version or commit SHA1 this issue occurred on
v0.82.19+ (It does not hang on Debug build, or when optimization is off in Release build)
 - Used configuration, e.g. ```dosbox.conf```
all defaults

**Additional context**

### PR DESCRIPTION
**Pull request by driver1998**
# Description

**Does this PR address some issue(s) ?**
Fixes #1418 

**Does this PR introduce new feature(s) ?**
Fixes hanging on startup on Windows ARM32, introduced from https://github.com/joncampbell123/dosbox-x/commit/2ff361fed30368b085a0797dd9aaa7e666d1a760.
Blocks access to dynarec on WinRT 8.x, until it is working properly.

**Are there any breaking changes ?**
No.

**Additional information**
Dynarec on Windows ARM32 works, but only on Windows 10.
Windows RT 8.x only runs ARMv7 Thumb-2 code, which we don't have a backend for.
Attempting to use dynarec on RT will result in an instant crash.

Related #1019

### CODE REVIEW

**Comment by joncampbell123** [comment]
Wouldn't it be better to detect which ARM CPU it's running and the mode on rather than guess from the Windows version?

Though I'm not fully familiar with ARM, my understanding is that Thumb mode is enabled when the LSB of the instruction pointer is set at least after a branch instruction. I'm not sure if that's reflected in the instruction pointer but it might be worth it to check. Or, since the compiler is generating Thumb instructions, perhaps there's an #ifdef to disable dynarec if compiling to Thumb mode.

**Comment by joncampbell123** [comment]
Second question is why changing val[8] in the segment structure to Bitu helps?

**Comment by driver1998** [comment]
For the first question: The compiler always compiles in Thumb mode. Before Windows 10, running non-Thumb mode code is not supported at all.

> "ARMNT" is the PE image type of ARMv7-Thumb2. Visual C++ uses the #define _M_ARM_NT, though _M_ARM is also #defined by the compiler. Windows RT never leaves Thumb2 mode. In fact, the context switch routines in the kernel set the Thumb bit of CPSR when saving the CPU context of a frozen task, meaning that any interrupt will cause an ARM program to crash when control returns.
> 
> Myriachan, from https://forum.xda-developers.com/showthread.php?t=2503498

The ban is lifted on Windows 10, probably a byproduct from supporting running Android apps on Windows 10 Mobile. But the compiler is still restricted in Thumb mode.

Overall running non-Thumb code in Windows is sort of a hack all along, maybe disabling it all together is a better way to go...

For the second question... I actually have no idea. I checked through the commits between v0.82.18 and v0.82.19 and found that this commit breaks it.

**Comment by joncampbell123** [comment]
Works for me...
If I were to purchase a Microsoft Surface to develop DOSBox-X and enable developer mode, would it allow me to develop Win32 non-UWP applications? Or is it UWP only and jailbreaking required?

**Comment by driver1998** [comment]
If you are talking about Surfaces with Windows RT (1 and 2), then yes, jailbreaking is required.
If you are talking about the new ARM64 tablets, like Surface Pro X, then Win32 is open regardless of developer mode. Developer mode is required for UWP development only.

Also if you have existing ARM SBC and boards, you might be able to spin up a KVM VM and run Windows 10 there.

**Comment by joncampbell123** [comment]
I just checked out a local store, and apparently MOST of the Surface X tablets are Intel x64 based. Only one of the display models had a ARM64 aka "Microsoft SQ1" CPU.

**Comment by joncampbell123** [comment]
Picked up an ARM64-based Surface. ARM and ARM64 builds run fine. However the window is freaking tiny on the high resolution display, so perhaps if Direct3D9/OpenGL output is enabled it might be wise to read screen DPI and pick a more appropriate default size.

**Pull request merged**
