### PR TITLE
Improvements to IMGMAKE command

### PR DESCRIPTION
**Pull request by Wengier**
The IMGMAKE command will show an error if you try to create a disk image file which already exists. I noticed that there is a -force option in DOSBox Optionals to overwrite the existing disk image file even if it already exists. I believe this is a useful addition so I added this to DOSBox-X too. Also, IMGMAKE will now use the default image file name "IMGMAKE.IMG" if no image file name is specified. In addition, I made some improvements to the help message for this command.

### CODE REVIEW

**Comment by joncampbell123** [comment]
Following up with the build system: I finished the update and my Linux system now has GCC 9.3 by default.

Development from this point on will be done with GCC 9.3, though I will stay at C++11 and keep a minimum off GCC 4.8.5 around for at least a year until nobody uses GCC 4.x anymore.

**Comment by Wengier** [comment]
@joncampbell123 I am glad to hear that. By the way, do you have time to look at Issue #1545? I am sure you are more familiar with the hardware/device driver part than me.

**Comment by joncampbell123** [comment]
That's going to take slow incremental work. The device driver selection code needs to enumerate the driver linked list, and then it's just a matter of constructing the various calls to the driver interrupt routine with the request structures.

**Comment by Wengier** [comment]
@joncampbell123 I see. And thanks for the link with details about DOS device drivers.

**Comment by joncampbell123** [comment]
@Wengier The good news is that I have a few books on my bookshelf that cover MS-DOS device drivers to varying degrees. Including "Advanced Assembly Language" that helped me write my first character device driver way back in the day. It was just a dumb driver that sent written data to the Sound Blaster DSP using DSP command 0x10 "direct write" :)

**Comment by Wengier** [comment]
That is a good thing for sure. I have not actually written a DOS device driver using the assembly language myself yet (I did use the assembly language for some other things). But in any case, once this feature is implemented, it will be become a very useful and unique feature of DOSBox-X - apparently no other DOSBox forks have supported this yet (many of them are very game centric of course).

**Pull request merged**
