### PR TITLE
Updated Spanish translation files for DosBox-X 0.83.11

### PR DESCRIPTION
**Pull request by Dalekamistoso**
Updated translation files in order to comply with updates to the user interface in the latest DOSBox-X (0.83.11)

Also I have deleted the old spanish SDL1 file in order to replace it with a shorter name.

### CODE REVIEW

**Comment by Wengier** [comment]
Thanks for the updates. I would suggestion change the name "sdl1" to something like "windows-sdl1" though because that type of menu is specific to Windows SDL1 builds, but not Linux SDL1. On the other hand, both macOS SDL1 and SDL2 builds use the macOS menu.

**Comment by joncampbell123** [comment]
There's a merge conflict for contrib/translations/es/es_ES.lng. Can you resolve that?

**Comment by Dalekamistoso** [comment]
I don´t have writing access to correct the conflict, it seems that Wengier made changes that affected the conflicting files.

https://github.com/joncampbell123/dosbox-x/commit/c2b5dc02bf9fef410f1475924aa1615fe8facb00

This is my fault because I was in a hurry I pushed directly into master because I was confident that nobody touched that folder, so I have already created a new pull request #2334 and I will close this one.

**Comment by Dalekamistoso** [comment]
I deleted this pull request and created a new one that solves the file name conflicts and adds the name change suggested by Wengier.

The new one is #2334

**Pull request closed without merging**
