### PR TITLE
Next SVN commits

### PR DESCRIPTION
**Pull request by Allofich**
https://sourceforge.net/p/dosbox/code-0/4099/ - Skipped. MAMEsound
https://sourceforge.net/p/dosbox/code-0/4100/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4101/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4102/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4103/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4104/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4105/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4106/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4107/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4108/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4109/ - Skipped. Copyright update.
https://sourceforge.net/p/dosbox/code-0/4110/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4111/ - Skipped. Conflicts with DOSBox-X
https://sourceforge.net/p/dosbox/code-0/4112/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4113/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4114/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4115/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4116/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4117/ - Already in DOSBox-X
https://sourceforge.net/p/dosbox/code-0/4118/ - Already in DOSBox-X
https://sourceforge.net/p/dosbox/code-0/4119/ - Already in DOSBox-X
https://sourceforge.net/p/dosbox/code-0/4120/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4121/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4122/ - In this PR
https://sourceforge.net/p/dosbox/code-0/4123/ - Skipped. Irrelevant.
https://sourceforge.net/p/dosbox/code-0/4124/ - Skipped. Irrelevant.
https://sourceforge.net/p/dosbox/code-0/4125/ - Skipped. Irrelevant.
https://sourceforge.net/p/dosbox/code-0/4126/ - Skipped. Irrelevant.
https://sourceforge.net/p/dosbox/code-0/4127/ - Skipped. Irrelevant.
https://sourceforge.net/p/dosbox/code-0/4128/ - In this PR

Compiles and runs.

### CODE REVIEW

**Comment by joncampbell123** [comment]
I know I don't quite have this formally specified yet, but I plan to make a binary release June 1st.

Starting May 28th please restrict pull requests to bug fixes only until after the June 1st binary release.

**Comment by Allofich** [comment]
Okay.

**Comment by Allofich** [comment]
I went through the remaining commits in mainline up until the latest one, which right now is r4228. I decided to just look for any fixes to the commits that have already been merged into DOSBox-X, but I didn't notice any, so I'll keep it at r4128 for now.

**Comment by Allofich** [comment]
In https://www.vogons.org/viewtopic.php?f=41&t=31881&sid=0a368f2ded9f5ddf1d03259845efe760&start=1800, a poster commented

> I believe the r4039 commit is not incorporated fully into dosbox-x. The code block is different between it and SVN. I can paste a suggestion, if needed.

SVN:
https://sourceforge.net/p/dosbox/code-0/4039/

As merged into DOSBox-X:
https://github.com/joncampbell123/dosbox-x/commit/79c3bd971912e2c32a3db6192ac7717a9096c340

The code from the r4039 commit is all there, but the order the code appears in the file is different, because I matched it to the order of the file in the DOSBox-X source.

**Pull request merged**
