### PR TITLE
Added -set command-line option to set config option(s), improved PC-98 mode 

### PR DESCRIPTION
**Pull request by Wengier**
There is currently no way to specify config option(s) when starting DOSBox-X, except by putting them in the config file. To overcome this I decided to add the -set command-line option to do achieve this. Like the -c command-line option, the -set command-line can be specified multiple times for multiple options, overriding any options in the config file. For example, the command:
 
``dosbox-x.exe -set machine=pc98``

Will start DOSBox-X in PC-98 mode regardless of the config setting in dosbox-x.conf.

``dosbox-x.exe -set machine=cga -set fullscreen=true``

Will start DOSBox-X in CGA mode and also in full-screen mode.

The usage of the -set command-line is the same as "config -set", so you can specify a section or property with spaces in quotes. For example:

``dosbox-x.exe -set "dos dos clipboard device enable=true"``

Will enable support for the CLIP$ device.

I also improved Shift-JIS support in PC-98 mode as mentioned in Issue #1515, including GetFileAttr, SetFileAttr, and DIR command in PC-98 LFN mode.

### CODE REVIEW

**Comment by joncampbell123** [comment]
The point of the host_cnv_char_t is to match the best datatype for the host system.

On Windows, host_cnv_char_t is wchar_t.
On anything else (Linux, Mac OS X) host_cnv_char_t is char to represent UTF-8.

CodePageGuestToHost() will convert the guest code page to wchar_t for Microsoft's widechar functions if compiled on Windows for that reason. The wrapper is unnecessary.

The guest <-> host conversion is supposed to be applied regardless of machine type (you check only for PC-98 mode). In IBM PC mode for example the code page conversion is to convert from CP437 (the DOS character set) to the host, and in PC-98 mode, Shift-JIS to the host.

Look at other functions in drive_local.cpp like MakeDir() for a good idea how to do this.

**Comment by joncampbell123** [comment]
Mind if I do the GetFileAttribute/SetFileAttribute work instead? Remove the "Improve PC-98 mode" fixes and I'll take care of that part, and merge the rest of the pull request.

**Comment by Wengier** [comment]
@joncampbell123 Of course I wanted to use CodePageGuestToHost() for all machine types in that function, but unfortunately CodePageGuestToHost() did not work well for that specific function, causing crashes if I do. That is why it took me some time to submit this pull request, and I had to add a CodePageHostToGuestL() help function for PC-98 mode too (otherwise it will crash too). I supposed there is some limitation in the CodePageGuestToHost() function for this case, so I have to reply on additional code to make it work reliably.

**Comment by Wengier** [comment]
@joncampbell123 The GetFileAttribute/SetFileAttribute case was not PC-98 specific though. The check for PC98 mode was done for something else (DIR in PC-98 LFN mode).

**Comment by Wengier** [comment]
@joncampbell123 Please check the code again. I am not checking for PC-98 mode for  GetFileAttribute/SetFileAttribute at all.

**Comment by Wengier** [comment]
The GetFileAttribute/SetFileAttribute work was only a small part of the patch. For these I did use CodePageGuestToHost() completely without any wrapper. The wrapper is for something else (as I mentioned earlier, for DIR in PC-98 LFN mode).

**Comment by joncampbell123** [comment]
Why the if (IS_PC98_ARCH) on line 1289? https://github.com/joncampbell123/dosbox-x/pull/1518/commits/a491457f9d745a328c8662cbd163a343b1f175f9#diff-d6c7e14d805837d969eb6f5c84972ae4R1289

And the other one farther down? https://github.com/joncampbell123/dosbox-x/commit/a491457f9d745a328c8662cbd163a343b1f175f9#diff-d6c7e14d805837d969eb6f5c84972ae4R1329

**Comment by Wengier** [comment]
@joncampbell123 The two "if (IS_PC98_ARCH)" are for FindFirst/FindNext, not GetFileAttribute/SetFileAttribute. GetFileAttribute/SetFileAttribute only needs CodePageGuestToHost() without any wrapper. But the FindFirst/FindNext fix is to make DIR show Shift-JS in PC-98 LFN mode correctly. For FindFirst/FindNext I cannot completely reply on the CodePageGuestToHost() function (otherwise it will cause crash), that is why I am adding "if (IS_PC98_ARCH)" for them.

**Comment by joncampbell123** [comment]
Hold on I get what's going on here. The CodePageHostToGuest() uses a global that's overwritten when called again, so the L version uses another global.

I'll go ahead and merge this but I also want to remove the if (IS_PC98_ARCH) because code page conversion going back should always use CodePageHostToGuest(). Currently for IBM PC mode, wcstombs() is used which converts to whatever non-unicode locale the user is using, NOT CP437 or Shift-JIS.

**Comment by Wengier** [comment]
@joncampbell123 In that function there are two names to convert, both SFN and LFN names (unlike in all other functions there is only one name to convert). And unfortunately CodePageHostToGuest() does not work for both names at the same time (if you tried to do both it will cause crash). Perhaps CodePageHostToGuest() needs to be fixed to do this properly, but for now I have to rely on this additional code to make it work stably.

**Comment by joncampbell123** [comment]
If you look at CodePageHostToGuest() and CodePageGuestToHost() farther up the source file, you'll see the convenience functions are just a C++ overload that calls the real function pointed at the cpcnv_temp global, which it then returns if success. The real functions accept a source and destination pointer. The dest pointer is assumed to be at lease CROSS_LEN bytes large.

**Comment by Wengier** [comment]
@joncampbell123 I noticed that already of course. There are at least two problems I encountered, one with the overload function, and the other with the real function. So I solved the first problem by adding a CodePageHostToGuestL() helper function, and the second problem was worked around by using "if (IS_PC98_ARCH)", although the proper way to fix the second problem is to fix the real CodePageHostToGuest() function itself.

**Comment by joncampbell123** [comment]
Does it show up as string corruption with an occasional segfault? Perhaps I need to revisit those functions in terms of the find first/next functions and LFNs to see if there are any problems I need to look for.

**Comment by Wengier** [comment]
@joncampbell123 Yes, that is what I encountered when I tried to completely reply on CodePageHostToGuest() in that function in the beginning. The whole DOSBox-X window may disappear with a segmentation fault message.

**Comment by joncampbell123** [comment]
I will test LFNs then, copying COMMAND.COM from a Windows 95 bootdisk now.

**Comment by Wengier** [comment]
@joncampbell123 You can just use the built-in COPY command for testing too in PC-98 LFN mode.

**Comment by joncampbell123** [comment]
command.com with ver=7.0 shows correct code page conversion for both SFNs and LFNs.

**Comment by Wengier** [comment]
I wondered if the main segmentation fault message was already fixed by calling to CodePageHostToGuestL() instead of CodePageHostToGuest(). You can experiment with changing CodePageHostToGuestL() back to CodePageHostToGuest(), and you will soon notice the crash.

**Comment by joncampbell123** [comment]
I'm noticing that Windows builds do not tolerate filenames with any non-ASCII characters.

One test I do for example is I type "EDIT ▒▒▒▒.TXT" (EDIT and then ALT+177, ALT+177, etc.) and see if the filename appears on the host as four gray blocks. Code 177 in code page 437 is the classic MS-DOS gray block code.

Windows builds turn it into something like _11DB6~1.TXT which is odd.

**Comment by Wengier** [comment]
@joncampbell123 I believe names like _11DB6~1.TXT are the real 8.3 names generated on Windows system. They will be represented as SFNs in DOSBox-X as is. But the true names will be shown as LFNs in DOSBox-X.

**Comment by joncampbell123** [comment]
I could probably fix this for Windows if I write the find first/find next Windows functions to ignore the alternate name if cFileName is short enough to fit into a 8.3 short name.

**Comment by Wengier** [comment]
@joncampbell123 I noticed that the latest commit d6bc616 will cause some files with Shift-JS names to not show up with DIR. On the other hand, the previous commit fe258a9 works in this case.

**Comment by joncampbell123** [comment]
I know... I'm trying to pin down why. I don't understand why it would make any difference.

**Comment by joncampbell123** [comment]
Fixed it.

**Comment by Wengier** [comment]
@joncampbell123 The new is_filename_8by3w function will filter out file names like ▒▒▒▒.TXT causing them to not show up in PC-98 mode. Also, it is recommended to change line 182 in cross.cpp:

``if (*fname == '.') fname++;``

To:

``if (*fname == L'.') fname++;``

So that MinGW will work properly (VS seems to work fine).

**Comment by joncampbell123** [comment]
There's no code point in Shift-JIS for PC-98 to represent ▒▒▒▒.TXT.

If you look at the console or log file, you should see:

    LOG: read_directory_next: Filename '▒▒▒▒.TXT' from host is non-representable on the guest filesystem through code page conversion

**Comment by Wengier** [comment]
If you disable the is_filename_8by3w function, that file will show up in the PC-98 mode though, with a name like _11DB6~1.TXT. Perhaps you can add a config option to use Windows 8.3 names whenever available?

**Comment by Wengier** [comment]
I think I will modify the code so that if the file name contains characters not representable in the current code page, AND there is already a Windows 8.3 file name available, then always use this file name so that the file will show up in the list. This situation can apply to other code pages too, not just PC-98 mode, so this change should be useful in general too.

**Pull request merged**
