### PR TITLE
Haiku patches

### PR DESCRIPTION
**Pull request by extrowerk**
# Description

Preliminary Haiku patches

**Does this PR address some issue(s) ?**

Nope

**Does this PR introduce new feature(s) ?**

Nope

**Are there any breaking changes ?**

Nope

**Additional information**

Build-test ok on x86-64 with SDL2 and fluidsynth1.

### CODE REVIEW

**Comment by extrowerk** [comment]
Heh, should i remove the whitespace changes?

**Comment by joncampbell123** [comment]
@extrowerk That would clean up the pull request some, yes.

**Comment by joncampbell123** [comment]
One more thing: dos_inc.h is very different from dos_inc.h in your pull request and it is shown as a massive conflict to resolve.

**Comment by extrowerk** [comment]
Ummm... what the heck is going on here...?

**Pull request closed without merging**
