### PR TITLE
Pentium III emulation

### PR DESCRIPTION
**Pull request by joncampbell123**
Add a summary of the change(s) brought by this PR here.

## What issue(s) does this PR address?

Pentium III emulation request #3179. This is not going to be quick or easy but it can be done incrementally.

## Does this PR introduce new feature(s)?

Pentium III emulation, SSE registers, SSE instructions and control registers, SSE enable bit in CR4, and MSRs.

### CODE REVIEW

**Comment by PythonBlue** [comment]
Having found this development branch, you might be happy to know I tested the code as it is now. That said, it appears it's currently not an option to boot with Pentium III set as the processor due to a CPU fault, at least that's the explanation I found when booting with a disk preinstalled with 98SE. This issue might also explain the still lacking results for my fringe use case, since I'm pretty sure that as a MIDI driver, the software of concern loads on boot.

**Comment by joncampbell123** [comment]
@PythonBlue I haven't added any actual SSE instructions to normal core, much less the FXSAVE/FXRESTOR instructions that Windows 98SE will need to task switch with SSE enabled. But thanks for testing. :laughing:

**Comment by PythonBlue** [comment]
> @PythonBlue I haven't added any actual SSE instructions to normal core yet, much less the FXSAVE/FXRESTOR instructions that Windows 98SE will need to task switch with SSE enabled. But thanks for testing. 😆
> 
> What I have done is set the framework to begin adding instructions, and I made sure the debugger can show the SSE instructions. So while the debugger recognizes one group of SSE instructions, normal core doesn't execute them yet.

Yeah, it took me having to see the description of this pull request while giving feedback to figure out that it's not even fully ready for testing yet. XD Thanks for the clarification. Needless to say, I am excited for this possibility when it's developed enough to be at least somewhat useable.

**Comment by qeeg** [comment]
According to the Intel SDM, SSE alignment exceptions are literally just GPFs. HTH.

**Comment by PythonBlue** [comment]
> According to the Intel SDM, SSE alignment exceptions are literally just GPFs. At least, it works for my emulator, PCBox. HTH.

I would consider PCBox as an alternative if it actually worked on a Mac. Alas, just built that from source due to no build for that platform being available, only to see that the menu bar necessary for changing settings beyond a 1981 IBM computer does not exist.

**Comment by qeeg** [comment]
I mean, there is a Qt port of the UI being worked on by 86Box, it's just taking some time. Please be patient.

**Comment by PythonBlue** [comment]
Just tried the latest commits out of excitement, and while it seems not all of the CPU opcodes may be implemented yet judging from the status of my use case, I'm happy to say that there is progress all the same insofar as testing: my Win98SE guest no longer crashes on startup when set to this new CPU type!

**Comment by PythonBlue** [comment]
> I mean, there is a Qt port of the UI being worked on by 86Box, it's just taking some time. Please be patient.

I'm guessing from this that you did see my response to your initial message, and I apologize for how blunt my words were at the time. From what I hear, it seems to be a plausible solution for Windows users: I was just a bit frustrated that PCBox is the only branch I could find of 86Box that supports Mac at all, and even then, that it was still a WIP. Still, I realize it was wrong to be that impatient about it, especially since the reason I care so much about Pentium III emulation has to do with future proofing from Apple Silicon some possible tools: I can get by perfectly fine with my current setup on an Intel Mac for the time being.

**Comment by joncampbell123** [comment]
> Just tried the latest commits out of excitement, and while it seems not all of the CPU opcodes may be implemented yet judging from the status of my use case, I'm happy to say that there is progress all the same insofar as testing: my Win98SE guest no longer crashes on startup when set to this new CPU type!

Yeah, and that's actually kind of weird, because I haven't yet added the instructions needed to save or restore SSE state (FXSAVE/FXRESTOR) and Windows ME boots just fine with it anyway (needing only an additional MSR to read "platform ID" for Pentium III?).

I suspect crashes will happen when you run anything that uses SSE.

**Comment by PythonBlue** [comment]
> > Just tried the latest commits out of excitement, and while it seems not all of the CPU opcodes may be implemented yet judging from the status of my use case, I'm happy to say that there is progress all the same insofar as testing: my Win98SE guest no longer crashes on startup when set to this new CPU type!
> 
> Yeah, and that's actually kind of weird, because I haven't yet added the instructions needed to save or restore SSE state (FXSAVE/FXRESTOR) and Windows ME boots just fine with it anyway (needing only an additional MSR to read "platform ID" for Pentium III?).
> 
> I suspect crashes will happen when you run anything that uses SSE.

Good to know that you didn't implement those particular instructions yet. Curious why it boots fine now, that in mind...

And yeah, probably true, though I do know that the MIDI driver I hope to operate is running fine despite some of its sounds requiring Pentium III instructions.

**Comment by joncampbell123** [comment]
Windows ME is leaving me confused here actually... it looks like it switched on bit 9 of CR4, because my SSE test program runs just fine in a DOS Box and as a 16-bit Windows 3.1 application (Win32s build crashes for some reason?) but nothing in the DOSBox log says anything about an invalid opcode.

Did Microsoft just retrofit the task switcher in Windows 98SE/ME with something to load/save SSE manually and just flat out ignore FXSAVE/FXRESTORE? I would have expected an Invalid Opcode exception by now trying to execute those instructions! For that matter, I also expected an invalid opcode exception for LDMXCSR and SDMXCSR (load/save MXCSR) since that's a pretty important register too! It's the SSE equivalent of the FPU control word.

**Comment by joncampbell123** [comment]
On a related note, I just found out that Pentium II and (WIP) Pentium III emulation was NOT reporting MMX support through CPUID! Maybe that's what Windows ME is confused about. Checking...

**Comment by joncampbell123** [comment]
While we're getting Pentium III emulation up, here's what my real Pentium III shows for CPUID.

There's clearly a lot there that DOSBox-X is not likely to implement for a long time, if ever. Especially support for > 4GB of RAM and PAE.

IMG_20220101_200423170 cpuid

**Comment by joncampbell123** [comment]
Also on real hardware, the FreeDOS debugger (or the Pentium III?) will apparently skip over the following instruction if it encounters RDMSR with a debugger.

The three mystery values queried by Windows ME on boot up:
IMG_20220101_201039731 rdmsr1
IMG_20220101_201039731 rdmsr2

**Comment by PythonBlue** [comment]
> While we're getting Pentium III emulation up, here's what my real Pentium III shows for CPUID.
> 
> There's clearly a lot there that DOSBox-X is not likely to implement for a long time, if ever. Especially support for > 4GB of RAM and PAE.
> 
> However my guess for stepping/model/family was right on!
> 
> IMG_20220101_200423170 cpuid

Understood about some things being unlikely to be implemented, though I doubt 4 GB RAM would be necessary for DosBox-X anyway given Windows 98SE, for instance, only supports up to 512 MB.

**Comment by joncampbell123** [comment]
It's one thing to go up to just below 4GB because DOSBox-X inherits DOSBox SVN code using minimally 32-bit datatypes for physical memory addresses. That was easy, in fact, I still think DOSBox SVN's paranoid 63MB limit is still excessively low, but the devs refused to budge when I argued about it (and a bug in xms.cpp related to that).

I think the original paranoia is old DOS/Windows 3.1 code that was stupid enough to return extended memory size in kilobytes as a signed 16-bit integer, which breaks when you have 32MB (32768KB) or more of memory in your system.

However to go beyond 4GB might be tougher. Developers seem to use "Bitu" whenever they feel like it, which happens to be 64-bit on 64-bit, but 32-bit on 32-bit, and PhysPt elsewhere.

Also remember that in 1998 or so, 64MB to 128MB was considered a lot of memory back then. DOSBox-X aims to emulate up until the Windows XP era (when Microsoft forced motherboards to drop ISA slots through the PC "standards"), which is when the average machine might have had 128MB to 512MB.

**Comment by joncampbell123** [comment]
Good news... Windows ME is deceitfully tolerant of such minimal SSE emulation but the Linux kernel is brutally honest about what it expects of a Pentium III, and that's *good*.

Right now I see it crash at startup attempting to execute FXSAVE/FXRESTOR.

**Comment by joncampbell123** [comment]
The Linux kernel apparently will require PREFETCHNTA/PREFETCH0/etc. if it sees a Pentium III. Okay.

**Comment by joncampbell123** [comment]
Hey, found an old copy of CPU-Z that RIGHT AWAY tries to use the MOVUPS instruction (and BSODs Windows doing it because I haven't added that one yet :laughing: ) so progress will be made with that one.

**Comment by PythonBlue** [comment]
> Hey, found an old copy of CPU-Z that RIGHT AWAY tries to use the MOVUPS instruction (and BSODs Windows doing it because I haven't added that one yet 😆 ) so progress will be made with that one.

Yeah, noticed the BSOD issue with the current commit, myself. That said, however, there is sort of good news for my use case in that the BSOD also happened when I disabled the MIDI driver's support for DirectSound, not just during bootup, so obviously we're touching on the required instructions.

**Comment by DSN9990** [comment]
@joncampbell123 Is PSE/PAE emulation really difficult to implement?

**Comment by joncampbell123** [comment]
@DSN9990 I'm not certain, it depends on how hardcoded everything is towards the 386-style page structure lookup.

**Comment by RNMB15** [comment]
I saw an MMX, SSE and SSE3 test program on twitter.

https://twitter.com/simk98l
https://drive.google.com/file/d/1DYTF9EY2w7BUK9xFuO8NR2xVY3Iq9ND-/view

**Pull request merged**
