### PR TITLE
Continuing on sdlmain.cpp cleanup: OpenGL part

### PR DESCRIPTION
**Pull request by ghost**
This is OpenGL part and some preparation/generalization for Direct3D part.

Many supplementary OpenGL related code still remains in sdlmain.cpp, this needs to be assessed and moved out as well but later, after all primary output code paths will be out.

Some D3D related files moved, correction for non-VS builds makefiles would be needed.

### CODE REVIEW

**Comment by aybe** [comment]
Currently code does not compile but I believe this is expected ?

**Comment by joncampbell123** [comment]
It compiles here on Linux.

I fixed the aspect ratio code to take the aspect ratio from the VGA emulation rather than assume 4:3.

What compiler warnings/errors are you getting?

**Comment by alexat** [comment]
Compiles at least on VS2017 @ mine. Please share error you get indeed.

**Comment by aybe** [comment]
```
3>sdlmain.obj : error LNK2019: unresolved external symbol "unsigned int __cdecl OUTPUT_SURFACE_GetBestMode(unsigned int)" (?OUTPUT_SURFACE_GetBestMode@@YAII@Z) referenced in function __catch$_SDL_main$1
3>sdlmain.obj : error LNK2019: unresolved external symbol "unsigned int __cdecl OUTPUT_SURFACE_SetSize(void)" (?OUTPUT_SURFACE_SetSize@@YAIXZ) referenced in function __catch$_SDL_main$1
3>C:\Dev\dosbox-x\vs2015\..\bin\Win32\Debug\/dosbox-x.exe : fatal error LNK1120: 2 unresolved externals
```
(develop branch)

**Comment by alexat** [comment]
Hm, are output_surface_sdl.cpp / output_surface_sdl2.cpp appear in the source list / properly compiling, these functions are in these two.

**Comment by aybe** [comment]
I only have the declaration functions of both methods.
https://github.com/joncampbell123/dosbox-x/blob/develop/src/output/output_surface.h#L7

**Comment by alexat** [comment]
Um, and
https://github.com/joncampbell123/dosbox-x/blob/develop/src/output/output_surface_sdl.cpp
https://github.com/joncampbell123/dosbox-x/blob/develop/src/output/output_surface_sdl2.cpp

**Comment by aybe** [comment]
Yes in fact they're on HDD,

but:

2018-06-30 20_15_30-window

Seems like you're not using VS since they're not on vcxproj:

https://github.com/joncampbell123/dosbox-x/commits/master/vs2015/dosbox-x.vcxproj

Is this correct ?

**Comment by aybe** [comment]
And to be precise, vs2015.

**Comment by alexat** [comment]
Oh. Seems like VS2017 uses only filters and does not modify vcxproj then... I don't have them in .vcxproj indeed but they do display and compile )

image

**Comment by alexat** [comment]
@aybe 
VS2017 Community, using vs2015 project files

**Comment by aybe** [comment]
Alright, at least I'll know where to look at in case it fails in the future 😃 

Lettings you guys finish the refactoring, tbh I'm left in the dust !

**Comment by alexat** [comment]
@aybe 
To be honest, I don't think it would really be 'finished' anytime soon ) 
I'll try to logically split it and reduce code duplication where I can, but converting it to classes is a whole other story.

**Pull request merged**
