### PR TITLE
Improvements to overlay drives

### PR DESCRIPTION
**Pull request by Wengier**
I have made further improvements to the recently supported overlay drives. For example, long filename support should now work more reliably on such drives than before, also fixed some other issues I found.

### CODE REVIEW

**Comment by Wengier** [comment]
Shift-JIS characters (Kana, Kanji, etc) are now supported for overlay drives in PC-98 mode, by using wide characters instead of regular ones.

**Comment by joncampbell123** [comment]
Where is host_cnv_use_wchar defined?

**Comment by Wengier** [comment]
@joncampbell123 host_cnv_use_wchar is defined in line 56 of drive_local.cpp. This definition was already there for quite some time I think.

**Comment by Wengier** [comment]
@rderooy The new message does show up in Windows, but I when I tried on Linux it did not show up indeed. I will submit a new pull request today including a fix for this Linux-specific issue.

**Comment by joncampbell123** [comment]
@Wengier Right. My mistake. For some reason grep didn't find it at all.

**Pull request merged**
