### PR TITLE
src/cpu: Implement hinting NOPs

### PR DESCRIPTION
**Pull request by Jookia**
On Pentium Pro and later, opcodes 0x0f 0x18 through 0x0f and 0x1f nops.
These were later defined to be prefetch and multi-byte nop instructions.

This fixes PR #3209 and adds a feature only I seem to care about.
It implements it on all CPU cores and tested on amd64 Linux.

Test assembly:

```org 100h
; Print Hello world
mov dx,msg
mov ah,9
int 21h
; Test all hints
db 0x0f, 0x18
db 0x0f, 0x19
db 0x0f, 0x1a
db 0x0f, 0x1b
db 0x0f, 0x1c
db 0x0f, 0x1d
db 0x0f, 0x1e
db 0x0f, 0x1f
; Test nops
nop
db 0x66, 0x90
db 0x0f, 0x1f
db 0x0f, 0x1f, 0x40, 0x0     
db 0x0f, 0x1f, 0x44, 0x0,  0x0       
db 0x66, 0x0f, 0x1f, 0x44, 0x0,  0x0 
db 0x0f, 0x1f, 0x80, 0x0,  0x0,  0x0, 0x0    
db 0x0f, 0x1f, 0x84, 0x0,  0x0,  0x0, 0x0, 0x0
db 0x66, 0x0f, 0x1f, 0x84, 0x0,  0x0, 0x0, 0x0, 0x0
db 0x66, 0x2e, 0x0f, 0x1f, 0x84, 0x0, 0x0, 0x0, 0x0, 0x0
; Quit
mov ah,4Ch
int 21h
msg db 'Hello, World!',0Dh,0Ah,'$'
```

Compile and test:

```
nasm -f bin test.asm -o out.com
out.com
```

### CODE REVIEW

**Comment by Jookia** [comment]
If this gets merged I'll have to update the wiki to not support for multi-byte nop and hinting nops.

**Comment by Wengier** [comment]
It is already merged. You can update the Wiki accordingly.

**Comment by Jookia** [comment]
I updated https://github.com/Wengier/dosbox-x-wiki/wiki/Guide:CPU-settings-in-DOSBox%E2%80%90X to add NOPL. Not sure if you get notified or that's the right place to notify it (I haven't edited a wiki before)

**Comment by rderooy** [comment]
@Jookia looks fine. Feel free to update other parts of the page if you feel something is missing or needs a better explanation.

**Comment by grapeli** [comment]
@Jookia 
Unfortunately, when booting linux (4.19.242) there is a kernel panic if `cputype=pentium_iii`. It boots correctly if cputype is set to `ppro_slow` or `pentium_ii`. This, of course, is related to this pull request.

[linux.zip](https://github.com/joncampbell123/dosbox-x/files/8692860/linux.zip)

`dosbox-x -set cputype=pentium_iii -set core=dynamic_x86 -set output=ttf -c "mount c ./lin" -c "c:" -c "linux.bat"`

The kernel was configured for Pentium-Classic.
```
CONFIG_M586TSC=y      #Processor family (Pentium-Classic)
CONFIG_X86_GENERIC=y  #Generic x86 support
```

**Comment by Jookia** [comment]
Please open a bug report for this. Thanks.

**Pull request merged**
